### ISSUE TITLE
Could you share your experience to train VGG which has ap=28.3 on coco_2014_minival?

### ISSUE THREAD

**Issue by KeyKy** [endernewton/tf-faster-rcnn#1]
Could you share your experience to train VGG which has ap=28.3 on coco_2014_minival? Thanks!
1.For coco, we find the performance improving with more iterations (790k), and potentially better performance can be achieved with even more iterations. The learning rate is?

**Comment by endernewton** [comment]
Everything is kept the same as the default script, except that you reduce the learning rate at 600k and finish training at 790k, with my code.
