### ISSUE TITLE
Why does image size matter ?

### ISSUE THREAD

**Issue by SamyMe** [endernewton/tf-faster-rcnn#102]
Hello,

I'm trying to test your implem' in my own images that are 1024*6144 (sometimes 2048*12288). 
When I try to run detection, I get some pretty bad results on the full image :
![demo_7](https://cloud.githubusercontent.com/assets/7459397/26363383/279785c0-3fe1-11e7-87f3-44b3e6b6c815.png)
When I lower the threshold:
![Uploading demo_67.png…]()
But when I cut the image, I get nearly perfect results:
![demo_29](https://cloud.githubusercontent.com/assets/7459397/26363398/366a5730-3fe1-11e7-9a6c-f579600beecc.png)
![demo_17](https://cloud.githubusercontent.com/assets/7459397/26363408/3ce5e11a-3fe1-11e7-8258-f43bdbe63bf8.png)

Resolution does matter ok, but why does image dimensions? and how can I deal with this?
Thank you !

**Comment by endernewton** [comment]
it is not the size but the aspect ratio.

**Comment by SamyMe** [comment]
And how comes it affects the detection ? Is the anchors aspect/ration dependent on that of the image or something like that ? (sorry for not being sharp enough)

**Comment by SamyMe** [comment]
I just changed  **__C.TEST.MAX_SIZE** in [config.py](https://github.com/endernewton/tf-faster-rcnn/blob/2e541afa65eec3152e50ee267c595bd58026e49b/lib/model/config.py) in and it works. Since Images get resized in [_get_image_blob(im)](https://github.com/endernewton/tf-faster-rcnn/blob/3fabcd1c66cd98d22e1c87a70fc6fcbdadbdfbc8/lib/model/test.py#L27) so that the larger dimension is at max **__C.TEST.MAX_SIZE**.
