### ISSUE TITLE
Model question.

### ISSUE THREAD

**Issue by kalaspuffar** [endernewton/tf-faster-rcnn#103]
Hi @endernewton

I've tried a number of the different implementations of faster-rcnn. And this seems to be the most living implementation which is really fun. I've also been able to do some changes in order to run my own data which is exciting.

But I have a question about the model and how the system works.

In my case I have images with boxes of some specific classification that I train the network with. They have an absolute position. My test data and validation data has boxes with absolute positioning of boxes as well so the only thing i really need the model to tell me is the classification of the boxes. And I believe that my data is such that the context around the boxes are important to determine the box classification.

Is using the RCNN model the right choice or have I complicated the issue. Is there a way to classify a region of an image with a simpler model?

Best regards
Daniel

**Comment by endernewton** [comment]
if background classes are not your concern, then just do image classification is fine.

**Comment by kalaspuffar** [comment]
Thanks for the quick response. I might not understand your answer or perhaps my question wasn't clear enough.

I have images with lets say 15 boxes. These boxes has 3-5 different classes. The boxes in the image could require the context around them. So box A might require the information that it's on the right side of box B to qualify it for consideration to be in class AB.

If I've understood image classification you look at one image and determine what the image is representing so in my example that would be classifying each box as one image. 

Or is there something I'm missing here?

**Comment by endernewton** [comment]
crop the image to some box and treat that as an image classification problem? if you want local context you can expand that box..
