### ISSUE TITLE
coco annotations missing? 

### ISSUE THREAD

**Issue by galactica147** [endernewton/tf-faster-rcnn#105]
Hi, I was following the training instructions as: `./experiments/scripts/train_faster_rcnn.sh ${GPU_ID} coco res101`, but got some errors: 

> IOError: [Errno 2] No such file or directory: '...tf-faster-rcnn/data/coco/annotations/instances_train2014.json'

I've installed (make) COCO API as suggested, but after that it didn't give this annotations/ directory.
Under /data/coco/, i have common/, results/ and several *API/ dirs. 
And under results/, i have: 

> captions_val2014_fakecap_results.json  
instances_val2014_fakebbox100_results.json  
instances_val2014_fakesegm100_results.json  
person_keypoints_val2014_fakekeypoints100_results.json  
val2014_fake_eval_res.txt

Did i miss anything here? 
Thanks!

**Comment by endernewton** [comment]
you need to download the training data at least..

**Comment by galactica147** [comment]
thanks xinlei!
