### ISSUE TITLE
How to get predicted class of every testing image?

### ISSUE THREAD

**Issue by HTLife** [endernewton/tf-faster-rcnn#109]
After I trained the network on my own dataset.
I'd like to print out the predicted class of every image in my test set, where could I find the related variables?

I found related peaces,
```
test_faster_rcnn.sh
==>./tools/test_net.py
====>./lib/model/test.py
def test_net_(sess, net, imdb, weights_filename, max_per_image=100, thresh=0.05):
...
_t['im_detect'].tic()
    scores, boxes = im_detect(sess, net, im)
    _t['im_detect'].toc()
```
but still cannot understand how to retrieve **predicted class** from `scores`.

p.s. Assume one image only contain one box, therefore, one prediction label.

**Comment by endernewton** [comment]
read more for the test functions. they should be in the main loop
