### ISSUE TITLE
Random results for custom image

### ISSUE THREAD

**Issue by horiabeschea** [endernewton/tf-faster-rcnn#11]
Hi,

I took  the code in from test_net() in lib/model/test.py and ran it on a custom image multiple times and print boxes.shape[0] after im_detect.
I get random results each run : sometimes 2 features detected, sometimes 4-6 or even 300.
Is this expected ? Is there something I can do to make it more predictable ?

Thanks

**Comment by endernewton** [comment]
This is odd, could you visualize the detected boxes? Should be easy to do with python opencv.

**Comment by horiabeschea** [comment]
I did the visualization and the boxes look good, but random. In an image with 3 people sometimes one is localized, sometimes the other.
I played with the config options for nms thresholds and I finally got it to work using __C.TEST.MODE = 'top' instead of nms. 
I'm running this on a mac, I'll try to replicate on Ubuntu, but closing this for now.

**Comment by endernewton** [comment]
Hmm this is still odd, maybe the nms is not working on your side, because given the scores for each box, nms should work deterministically. Can you check if you have compiled with the right gpu arch?
