### ISSUE TITLE
RuntimeWarning: invalid value encountered in greater_equal keep = np.where((ws >= min_size) & (hs >= min_size))[0]

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#114]
I'm trying to run faster_rcnn on another dataset based on pascal VOC format. But this is how the training turns out to be like:

![bbb6ca32-4706-11e7-9893-f10369b04492](https://cloud.githubusercontent.com/assets/24352869/26691591/f56cab50-4712-11e7-917a-adf67c79be7d.png)

As you see, the total loss value is changing in a weird way and after the warning it becomes nan. What can I do to make it right?

(gpu: Geforce 940m)

**Comment by endernewton** [comment]
still not my repo. closing.

**Comment by meetshah1995** [comment]
Any fixes to this?
