### ISSUE TITLE
Low and weird mAP results on new dataset

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#117]
I have trained faster rcnn on a new dataset based on pascal_VOC format. The configurations are like pascal_VOC but there are 9 classes and the training is done with **10000 iterations**. This is the results:

```
AP for car = 0.5931
AP for truck = 0.3333
AP for tractor = 0.3470
AP for campingcar = 0.4091
AP for van = 0.5000
AP for other = 0.1983
AP for pickup = 0.3439
AP for boat = 0.0769
AP for plane = -1.0000
Mean AP = 0.2002
```

As you can see the AP values are very low, and for objects of type **plane** , it's **-1**. What can cause this? Should I change anything else to improve the AP values?

**Comment by endernewton** [comment]
you haven't provided full info for your customized setting. -1 usually means no testing data?
