### ISSUE TITLE
The proposal boxes count are different for the same image when I run the demo code

### ISSUE THREAD

**Issue by rolai** [endernewton/tf-faster-rcnn#118]
When I run the demo code for a image twice, in the first time the faster-rcnn model return 300 proposal boxes, the second time return 214 boxes.  Is there any configuration to setup?

And I try to run the test script **test_faster_rcnn.s**h for the same test dataset many times, the Mean AP changes! Is there something wrong happens?

**Comment by endernewton** [comment]
can you get the exact test number for voc?

-Xinlei

**Comment by rolai** [comment]
Solve the problem after set USE_GPU_NMS to False
