### ISSUE TITLE
How to draw detected bounding boxes on test images of Pascal_VOC like demo?

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#122]
I would appreciate it if anyone could help me with this. When one runs **demo.py**, after the training the test images are shown and there are bounding boxes with labels around the detected objects. This is the function which does this:

```
def vis_detections(im, class_name, dets, thresh=0.5):
    """Draw detected bounding boxes."""
    inds = np.where(dets[:, -1] >= thresh)[0]
    if len(inds) == 0:
        return

    im = im[:, :, (2, 1, 0)]
    fig, ax = plt.subplots(figsize=(12, 12))
    ax.imshow(im, aspect='equal')
    for i in inds:
        bbox = dets[i, :4]
        score = dets[i, -1]

        ax.add_patch(
            plt.Rectangle((bbox[0], bbox[1]),
                          bbox[2] - bbox[0],
                          bbox[3] - bbox[1], fill=False,
                          edgecolor='red', linewidth=3.5)
            )
        ax.text(bbox[0], bbox[1] - 2,
                '{:s} {:.3f}'.format(class_name, score),
                bbox=dict(facecolor='blue', alpha=0.5),
                fontsize=14, color='white')

    ax.set_title(('{} detections with '
                  'p({} | box) >= {:.1f}').format(class_name, class_name,
                                                  thresh),
                  fontsize=14)
    plt.axis('off')
    plt.tight_layout()
    plt.draw()
```

My question is if one wanted to do the same on some of the testing images of **pascal_VOC** dataset, in which file should this function be written, and what changes are necessary to make it work with pascal?

**Comment by endernewton** [comment]
instead of the provided demo images, you just do it for all the voc images (find the folder yourself)

**Comment by hadi-ghnd** [comment]
@endernewton thanks for your reply. The `demo.py` file runs on demo images here:

   ```
 im_file = os.path.join(cfg.DATA_DIR, 'demo', image_name)
    im = cv2.imread(im_file)
```

I'm running psacal by this command on your page:
`./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc vgg16`

so you mean I should add functions from `demo.py` to `train_faster_rcnn.sh` and change the path to pascal test images?
