### ISSUE TITLE
The eval APs are zero on my custom data-set. 

### ISSUE THREAD

**Issue by hzycn** [endernewton/tf-faster-rcnn#126]
My dataset is same as VOC2007, and I only changed the class name parameters in lib/dataset/pascal_voc.py. The result is below:
Writing vertebraa VOC results file
VOC07 metric? Yes
/home/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py:204: RuntimeWarning: invalid value encountered in true_divide
  rec = tp / float(npos)
/home/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py:45: RuntimeWarning: invalid value encountered in greater_equal
  if np.sum(rec >= t) == 0:
AP for nf = 0.0000
AP for nfs = 0.0000
AP for disc = 0.0000
AP for disca = 0.0000
AP for vertebra = 0.0000
AP for vertebraa = 0.0000
Mean AP = 0.0000

**Comment by endernewton** [comment]
npos is zero. You don't have positive boxes loaded.

**Comment by hzycn** [comment]
How do I load positive boxes?  I did not change codes.

**Comment by endernewton** [comment]
you have a custom dataset, you should have changed the code to load that dataset.. check that

**Comment by hzycn** [comment]
Ok, thanks again. I will try it.

**Comment by zdm123** [comment]
@hzycn  hi， how ddi you solve the problem?

**Comment by Leerw** [comment]
Hi!After my training on my own dataset, it said my background AP is 0 and my interest class AP is 0.905, so I wanna know why the background AP is 0 and does it matter?

**Comment by Leerw** [comment]
Here is the text:
> AP for __backgroud__ = 0.0000  
> AP for myclass = 0.9025
> Mean AP = 0.4513
>~~~~~~~~
>Results:
>0.000
>0.903
>0.451
>~~~~~~~~

**Comment by zhuyabin** [comment]
@hzycn hi, i have same problem in my own datasets. How do you solve this problem?

**Comment by zhuyabin** [comment]
My model has been trained to complete.It's good to test it with demo,but ./experiments/scripts/test_faster_rcnn.sh 3  pascal_voc vgg16  is bad.
im_detect: 1/6 4.758s 0.001s
im_detect: 2/6 2.646s 0.001s
im_detect: 3/6 1.939s 0.002s
im_detect: 4/6 1.588s 0.001s
im_detect: 5/6 1.377s 0.001s
im_detect: 6/6 1.237s 0.001s
Evaluating detections
Writing butterfly VOC results file
VOC07 metric? Yes
0
/home/zhuyabin/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py:215: RuntimeWarning: invalid value encountered in true_divide
  rec = tp / float(npos)
/home/zhuyabin/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py:46: RuntimeWarning: invalid value encountered in greater_equal
  if np.sum(rec >= t) == 0:
AP for butterfly = 0.0000
Mean AP = 0.0000
~~~~~~~~
Results:
0.000
0.000
~~~~~~~~

**Comment by Lj10086** [comment]
I was able to install the tensorflow from the source as endernewton's repo guided. And I tried to use the tensorboard comes with it and the new version of tensorboard 1.14.1, but it seems the epoch-accuracy curve option is still missing. Any idea where and how to configure to have the accuracy data recorded and displayed in the tensorboard? Thanks,
