### ISSUE TITLE
COCO evaluation does not work if the category IDs in the annotation file are not in correct order

### ISSUE THREAD

**Issue by mubastan** [endernewton/tf-faster-rcnn#128]
The recall/precision values are wrong (totally junk) if the category IDs are not in order in the ground truth annotation file (or put another way: they are in different order in training and test set annotation file).

I am not sure if this is an expected behavior or a bug and whether it is in COCO API or the interface to it.
Just wanted to note it, if someone encounters the same issue, quick fix: just edit the annotation files (train/val/test) and make sure the category IDs are in correct order (1, 2, 3,...,#classes).

**Comment by endernewton** [comment]
thanks @mubastan!
