### ISSUE TITLE
only use RPN

### ISSUE THREAD

**Issue by w39865008** [endernewton/tf-faster-rcnn#129]
How to only use RPN?  Only change the file "vgg16"? Thanks.

**Comment by philokey** [comment]
What do you mean? RPN is a basic module in faster-rcnn, it use RPN to generate proposals.

**Comment by w39865008** [comment]
The paper "Is Faster R-CNN Doing Well for Pedestrian Detection?"  proposes RPN is good to detect pedestrian. Faster R-CNN is RPN+rcnn. So I want to use RPN to finish detection.  I find RPN module is in the file 'vgg16.py'.  How to only RPN to detect object? Thank you.

**Comment by endernewton** [comment]
for single-class object detection you can just take the rpn result out.  check the code [here](https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/nets/vgg16.py#L55).
