### ISSUE TITLE
How to test output models on new data?

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#130]
This is more of a question than an issue, but I would appreciate if you could help me with it.
Based on the instructions on the page, to test a network on a dataset, one can use a command like this:
`./experiments/scripts/test_faster_rcnn.sh $GPU_ID pascal_voc_0712 res101`

but what if one wanted to test the output models of the training (e.g `tf-faster-rcnn/output/vgg16/voc_2007_trainval/vgg16_faoster_rcnn_iter_40000.ckpt`) on some new images to see the results and to see if there have been enough iterations? Should I modify a file like **demo.py** to run on new images?

thanks

**Comment by philokey** [comment]
You should replace `im_names` with your own images and replace `NETS ` to your own model.

**Comment by hadi-ghnd** [comment]
@Philokey thanks for the helpful answer. I am trying to make **demo ** to work with the custom data. Do you think there is a more accurate way to decide on the  number of iterations? for example a chart of error value to see where it stops changing. I couldn't find this in **tensorboard**.

**Comment by philokey** [comment]
You can try to add the feature and pull request.

**Comment by hadi-ghnd** [comment]
@philokey I have modified the `demo.py` as you suggested and it's working on my model as well. But it opens a separate image for each class. For example if image **0001** had 3 type of classes, it would open **0001** three times and draw bounding boxes around detected object of each class in a corresponding image. Is it possible to visualize all classes of an image, in a single case all at once?

**Comment by endernewton** [comment]
thanks @philokey for the help! @hadi-ghnd you can find some good libs like opencv-python to draw bboxes yourself.
