### ISSUE TITLE
Anchor rations and anchor scales for res50

### ISSUE THREAD

**Issue by jureso** [endernewton/tf-faster-rcnn#132]
Hi.

I have downloaded the COCO res50 models. When I try to load the network, the expected number of anchors is 60 (I assume scales [2,4,8,16,32] and ratios [0.5,1,2]). However, this is not documented anywhere. It would be great if the training scripts for this models are also provided so we can recreate the setup. 

Thanks!

**Comment by philokey** [comment]
You can modify ratios and scales in `tf-faster-rcnn/experiments/scripts/train_faster_rcnn.sh`
