### ISSUE TITLE
Why can NOT list multiple scales

### ISSUE THREAD

**Issue by elias-1** [endernewton/tf-faster-rcnn#133]
I don‘t know why can NOT list multiple scales [code is here](https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/model/config.py#L61)

**Comment by philokey** [comment]
I think you can ignore the comment. In fact, during every training batch, it random select one scale of these scales.

**Comment by endernewton** [comment]
for training the code should be able to do it correctly, i was intending to warn people about testing, where only a single scale is supported. also if you do multi-scale, you may need to train longer.
