### ISSUE TITLE
How to draw detected bounding boxes from all objects in a single image?

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#136]
When I run the `demo.py` to test the model, it brings a separate image for each class of objects and draws the detected objects of that class only. Then for each of the other classes in the same image, it brings another image. If one wanted to draw bounding boxes from all the classes in one single image, witch part of the code should be changed?
Should I refer to the demo file from the original [faster rcnn page](https://github.com/smallcorgi/Faster-RCNN_TF/blob/master/tools/demo.py) or there is a simpler modification?

thanks

**Comment by hadi-ghnd** [comment]
I did this by moving these 3 lines:
```
im = im[:, :, (2, 1, 0)]
    fig, ax = plt.subplots(figsize=(12, 12))
    ax.imshow(im, aspect='equal')
```

to  `vedai` function.

**Comment by Liang-Jeff** [comment]
hello, I have met the same question. I think you might have solved this problem. Do you mean you creat a new function 
`def vedai():  `
    `im = im[:, :, (2, 1, 0)]`  
    `fig, ax = plt.subplots(figsize=(12, 12))`
    `ax.imshow(im, aspect='equal')`
My question is where to use this function, can you help me? thx.

**Comment by hadi-ghnd** [comment]
@Liang-Jeff I'm sorry my comment had a mistake. I did correct it. By `vedai` I meant `demo` function. I didn't add anything for that purpose.
