### ISSUE TITLE
Could you please tell what is the value of iou_threshold, score_threshold and nms_threshold when you want to evaluate your network?

### ISSUE THREAD

**Issue by mohammad-py** [endernewton/tf-faster-rcnn#137]
Hi @endernewton. I have written an object detector. I would like to validate it on mscoco dataset. Could you please tell me what are the value of:
1. `iou_threshold`
2. `score_threshold`
3. `nms_threshold`

Appreciating in advance for your response!

**Comment by JRCondeNast** [comment]
1. By looking at code coco data were evaluated at 10 iou_threhold which is  [0.5, 0.05,0.95]. But for VOC data it is only evaluated with iou>0.5
2. After applying nms only top 300 RPN were used at testing time so I assume there is no explicit cutoff for object versus no object score.
3. nms_treshold for test is 0.7
@endernewton corrected me if I'm wrong. @mohammad-py Hope this is helpful.

**Comment by endernewton** [comment]
thanks @JRCondeNast! closing
