### ISSUE TITLE
How to do data augmentations like flipping?

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#138]
I'm trying to perform some data augmentations (e.g rotation) on the training data. the instructions say the only option is to **left-right flipping** by setting the **C.TRAIN.USE_FLIPPED** flag to true. But I can't find where this flag is used? And how could I add some other techniques like **rotation** to increase training data for some classes?

thanks

**Comment by endernewton** [comment]
https://github.com/endernewton/tf-faster-rcnn/search?utf8=%E2%9C%93&q=TRAIN.USE_FLIPPED&type=
