### ISSUE TITLE
height/width factor computation

### ISSUE THREAD

**Issue by lichengunc** [endernewton/tf-faster-rcnn#143]
Why do we need do "**-1**" for the relative location computation?
i.e., height = (conv5_height **- 1**)*16, then x_factor = x/height 
in the function "def crop_pool_layer(self, bottom, rois, name)"

**Comment by endernewton** [comment]
it is just from the tf documentation: https://www.tensorflow.org/api_docs/python/tf/image/crop_and_resize. y is mapped to y * (conv_height - 1) to get the final coordinates.

**Comment by chrert** [comment]
This seems to be wrong anyway. Why not simply use `tf.shape(self._image)` or `self._im_info` instead? For example, if I pass an 800x600 image through the network, the current version computes `height = 592`and `width= 784` for VGG16. However, the box coordinates are in the range of the input image shape.

**Comment by endernewton** [comment]
it is good to think about it and do experiments to verify it actually.
there is the problem of misalignment at the beginning and at the end as
well. the pooling operation on VGG16 makes the story more complicated. i
have tried quite a few settings on my side before, and followed the current
setting from the original py-faster-rcnn. but do let me know if you find
better settings. :)

-Xinlei

**Comment by chrert** [comment]
Well, I think it's just a minor issue, but intuitively it looks like a bug to me  – at least for the `tf.crop_and_resize` implementation. I will let you know if I experience any major differences.

**Comment by endernewton** [comment]
Cool!
