### ISSUE TITLE
Resnet conv4/conv5 layer

### ISSUE THREAD

**Issue by JeGa** [endernewton/tf-faster-rcnn#146]
Could you give me a hint why when using resnet the region proposal is done on the conv4 layer (block3 in the code) and not on the last resnet layer? And why the conv5 block is then applied after the pool5 layer?

For comparison, when using vgg the region proposal is done on the last vgg layer.

Thanks!

**Comment by endernewton** [comment]
it is following the papers. for resnet you can also try to use the conv5 block and set the correct resolution, add two fc layers.  vgg16 it is not done on the last layer, but rather on the last conv layer. fc layers in vgg16 are used for region classification.
