### ISSUE TITLE
How to use earlier convolutional layers of VGG16 as input to the RPN?

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#147]
I wanted to run faster rcnn on a custom dataset other than pascal VOC. But the **VGG16** pretrained model isn't suitable for all sorts of data. So if I wanted to use another model or input the
**conv3_3** and **conv4_3** activation maps into the RPN module, instead of **conv5_3**.
what's the best way to do that?  I'm new to deep learning with tensorflow and would appreciate an expert's opinion on this.
thanks

**Comment by endernewton** [comment]
just wire the conv features you want to replace conv5_3.. not sure how to explain that in a more simple way..
