### ISSUE TITLE
ImportError: cannot import name resnet_v1_block

### ISSUE THREAD

**Issue by FPerezHernandez92** [endernewton/tf-faster-rcnn#148]
Hi. I'm follow the tutorial, and in the part: Demo and Test with pre-trained models, when I do:
CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py

I have the next error and I don't know why:
Traceback (most recent call last):
  File "./tools/demo.py", line 31, in <module>
    from nets.resnet_v1 import resnetv1
  File "/home/fperez/tf-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 16, in <module>
    from tensorflow.contrib.slim.python.slim.nets.resnet_v1 import resnet_v1_block
ImportError: cannot import name resnet_v1_block

I do, all step fine. Sorry for the inconvenience

**Comment by ntuloser** [comment]
resnet_v1_block is provided in Tensorflow 1.2.0 (not sure about 1.1 )
And yes, you are right, this might need to be added to README

**Comment by endernewton** [comment]
@ntuloser okay i will update readme then. closing.

**Comment by a3551571** [comment]
@endernewton @FPerezHernandez92 @ntuloser 
excuse me.
My tensorflow version is 1.0.Could you tell me how can I run the demo.py?I met the same problem:ImportError: cannot import name resnet_v1_block
Thanks a lot!

**Comment by ShHsLin** [comment]
The easiest way is to update to 1.2. 
You can also checkout the history of lib/nets/resnet_v1.py and rollback before  Jun 29, 2017

**Comment by endernewton** [comment]
i created a separate branch https://github.com/endernewton/tf-faster-rcnn/tree/r1.0 for 1.0

**Comment by a3551571** [comment]
@endernewton 
Thanks a lot!

**Comment by a3551571** [comment]
@ShHsLin 
OK.I have solved this problem.Thank you!

**Comment by zdm123** [comment]
@a3551571 sorry, I do not find any difference between v1.2 and v1.0. How to fix this problem.

**Comment by a3551571** [comment]
I use v1.0,Then I run it successfully.

**Comment by a3551571** [comment]
@zdm123

**Comment by zdm123** [comment]
@a3551571  I also use v1.0, and follow the steps, but still have the same problem.

**Comment by zdm123** [comment]
@a3551571  how did you solve the problem finally?

**Comment by Po-Hsuan-Huang** [comment]
@zdm123  You need to git checkout the history of lib/nets/resnet_v1.py and rollback before Jun 29, 2017, as mentioned by ShHsLin
