### ISSUE TITLE
Removing `'is_training': False` makes inaccurate result

### ISSUE THREAD

**Issue by rmekdma** [endernewton/tf-faster-rcnn#149]
Yesterday, I clone the repo and followed the demo instructions.
However, result was pretty bad and mAP over VOC2007 was 0.14.
After struggle, I found that restoring `'is_training': False` in resnet model make things work well.

That change occurred in the latest commit. 
https://github.com/endernewton/tf-faster-rcnn/commit/1f764f5ce90c11f212f982c5527a37b47cf635a7#diff-07b2efae5cf5470673af00d276270487L35

**Comment by endernewton** [comment]
thanks and sorry for the trouble caused on your side. i have restored that.

**Comment by rmekdma** [comment]
Should I set the parameter to True when I train a new model?

2017. 7. 6. 오후 2:47에 "Xinlei Chen" <notifications@github.com>님이 작성:

thanks and sorry for the trouble caused on your side. i have restored that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/endernewton/tf-faster-rcnn/issues/149#issuecomment-313301930>,
or mute the thread

**Comment by endernewton** [comment]
i don't think so. the batch norm parameters are not affecting accuracy that much on coco/voc, and fixing them can reduce training time.
