### ISSUE TITLE
What is the purpose of "fix_variables'?

### ISSUE THREAD

**Issue by TheodoreG** [endernewton/tf-faster-rcnn#150]
I have changed the crop pooling function in "network.py" so that the layer "pool5" has shape (256, 7, 7, 1536=3*512) instead of (256, 7, 7, 512). But when I run the code to train a new faster-rcnn model it indicates that in "fix_variables(self, sess, pretrained_model)" the shapes are consistent. I see that this function gets "fc6_conv" tensor from pretrained  vgg16 model with shape [7, 7, 512, 4096]. I am wondering how can the "fc6_conv" layer of pretrained vgg16 has shape exactly with "fc6" layer in original faster-rcnn model? Could anyone explain that to me?

**Comment by endernewton** [comment]
it just to make the network treating fc6/7 layers as fc layers, not conv layers, which works faster in previous tf versions. i was told that in the more recent versions they have fixed this issue and use fc operations when feasible. another reason is rgb to bgr swap.
