### ISSUE TITLE
Wrong image size due to PIL.Image open/close

### ISSUE THREAD

**Issue by mubastan** [endernewton/tf-faster-rcnn#151]
I am using the latest version of tf-faster-rcnn with PIL version 1.1.7.
While training a VGG16 model on PASCAL VOC 2007 with "flipped" images in the training set, I got assertion in **imdb.py**, `append_flipped_images` function, line `assert (boxes[:,2] >= boxes[:, 0]).all()`.

I debugged the code and found out that the problem was due to wrong image sizes returned by `_get_widths` function (strangely, only for some images). The 'boxes' was defined as numpy uint16 array (16 bit unsigned integer), which wraps around in negative values to a large positive values, and hence the assertion! The problem was solved when I modified the code so that each opened image is also closed.

```
image = PIL.Image.open(imageFile)
width = image.size[0]
image.close()
```
The same modification is (most probably) needed in **roidb.py** file, which contains similar code to extract image sizes, to avoid unexpected behavior.

**Comment by endernewton** [comment]
Oh got it, thanks for reporting this issue!!

**Comment by FMsunyh** [comment]
Same issue. I have give up to debug this repo. I got many issue when I run this repo.
