### ISSUE TITLE
Which python files are about RPN and ROI pooling layer in your Faster RCNN code?

### ISSUE THREAD

**Issue by wmf1991yeah** [endernewton/tf-faster-rcnn#153]
Thank you share your work! I am studying your code. I found a RPN and ROI pooling layer are set in Faster RCNN, I searched your code file but not found them.  Which python files are about RPN and ROI pooling layer in your Faster RCNN code? Please instruct me. Thank you very much!

**Comment by endernewton** [comment]
It is in the network definitions.. you can search for vgg16 for example.
