### ISSUE TITLE
How to resume from previous training?

### ISSUE THREAD

**Issue by jwnsu** [endernewton/tf-faster-rcnn#155]
readme file mentioned resume of training. However, it does not do so by default (default behavior is start all over again) and see no flag to do so either. Thx.

**Comment by endernewton** [comment]
Just use the same command line. It will check existing snapshots and reload.

**Comment by jwnsu** [comment]
Thx. There seems to be a rare bug somewhere, my previous run was aborted (not able to delete an older snapshot -- deleted manually), when restart with same command, it starts a new run. Just tried normal run, resume works fine.

**Comment by christianvari** [comment]
Hello, I have the same problem. It doesn't it by using the same command line. It starts again... Where is the resume flag stored?

**Comment by rnsandeep** [comment]
Its restarts from the already saved model if any if you use the same command. Check if it had already saved any model, it saves for every 5k iterations.

**Comment by punkkauz** [comment]
> Its restarts from the already saved model if any if you use the same command. Check if it had already saved any model, it saves for every 5k iterations.

after 5000 iterations really??

**Comment by saurabhg476** [comment]
You can change this flag "__C.TRAIN.SNAPSHOT_ITERS" in the config file for saving the snapshot according to the number of iterations.
