### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ghostcow** [endernewton/tf-faster-rcnn#156]
Hi, 

The link  http://ladoga.graphics.cs.cmu.edu/xinleic/tf-faster-rcnn/res101/voc_0712_80k-110k.tgz is broken.

**Comment by endernewton** [comment]
Sorry about that. The server crashes a lot especially when people download models. You can check other backup servers.

**Comment by lexuszhi1990** [comment]
@endernewton hi,  are the models on the google drive latest? if not, would you mind uploading them on it, thanks a lot

**Comment by endernewton** [comment]
they are.

**Comment by puneetjindal** [comment]
@endernewton : It will be really great if you can provide the script to download from Google Drive link shared on the repo

**Comment by SniperZhao** [comment]
the downloading is painful
