### ISSUE TITLE
Not using my GPU

### ISSUE THREAD

**Issue by fotherda** [endernewton/tf-faster-rcnn#157]
Any ideas why it's not using my GPU during training or testing. It's loaded the process correctly but just not using the GPU see output from nvidia-smi below:

+------------------------------------------------------+
| NVIDIA-SMI 352.93     Driver Version: 352.93         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           On   | 0000:00:03.0     Off |                  N/A |
| N/A   42C    P0    46W / 125W |     86MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      8483    C   python                                          73MiB |
+-----------------------------------------------------------------------------+

**Comment by endernewton** [comment]
maybe u need to install the gpu version of tf
