### ISSUE TITLE
How to display all the classes in one picture.

### ISSUE THREAD

**Issue by Liang-Jeff** [endernewton/tf-faster-rcnn#158]
Hi, thank you for your code. I'm trying to run the **./tools/demo.py** [code.](https://github.com/smallcorgi/Faster-RCNN_TF/blob/master/tools/demo.py) This code displays each class in a new picture. If I have 5 classes in a picture, I'll get 5 pictures. Because I'm new to the tf code, I find it hard to **modify the demo.py code to display all the classes in one picture**. Can anybody help me? Thanks

**Comment by endernewton** [comment]
check the current code of visualization at https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/utils/visualization.py. it is a hacked version displaying all object bboxes in one image.

**Comment by zhilaAI** [comment]
I have this code, but does not work for me. is there any solution?Thanks
