### ISSUE TITLE
Can some other dataset be used to train your Faster RCNN?

### ISSUE THREAD

**Issue by usman092** [endernewton/tf-faster-rcnn#159]
I want to use a custom dataset for training. I can train VGG16 or RESNET using my dataset but can I use it with this implementation of Faster RCNN?

**Comment by TheRevanchist** [comment]
I am doing it right now, and seems that it should work with some minor modifications. The easiest way seem to be by structuring your data in the same format as Pascal VOC, and then writing a file for your data similar to pascal_voc.py while also changing the factory.py and train/test_faster_rcnn.sh.

The changes seem to be straightforward, and a more detailed guide can be found here: https://github.com/zeyuanxy/fast-rcnn

it uses the rcnn official code, but it should work with this code too, considering that the code has been based on the official one.

**Comment by endernewton** [comment]
thanks @TheRevanchist, closing.
