### ISSUE TITLE
Problem loading model

### ISSUE THREAD

**Issue by andresrommier** [endernewton/tf-faster-rcnn#16]
I am trying to run the training script but when it tries to load the `vgg16.ckpt` file I get the following error:

```
F ./tensorflow/core/util/tensor_slice_reader.h:168] Check failed: sss_[idx]->Get(key, &value) Failed to seek to the record for tensor vgg_16/fc6/weights, slice -:-:-:-: computed key =
./experiments/scripts/train_faster_rcnn.sh: line 75:  5508 Aborted                 (core dumped) CUDA_VISIBLE_DEVICES=${GPU_ID} python ./tools/trainval_net.py --weight data/imagenet_weights/${NET}.ckpt --imdb ${TRAIN_IMDB} --imdbval ${TEST_IMDB} --iters ${ITERS} --cfg experiments/cfgs/${NET}.yml --net ${NET} --set TRAIN.STEPSIZE ${STEPSIZE} ${EXTRA_ARGS}
```

I am running Tensorflow 1.0 with CUDA 8.0 on a GTX 1070.

**Comment by endernewton** [comment]
I do not have GTX here and seems I cannot reproduce the error. Sorry.

**Comment by SnShine** [comment]
If the error arises when loading the file, most probably you might not have enough GPU memory. I guess vgg16 trained on voc0712 uses 4.7 GB of GPU memory.

**Comment by kalaspuffar** [comment]
@SnShine you might be right but then again GTX 1070 have 8 GB memory in the standard configuration. I run the same card without any problem.

@andresrommier My recommendation is trying to upgrade your tensorflow to 1.1 or newer. I got some strange errors with older versions but it seems that tensorflow and this repo has stabilized in newer versions.
