### ISSUE TITLE
get zero division errors 

### ISSUE THREAD

**Issue by huanhuanxuxu** [endernewton/tf-faster-rcnn#160]
after training with ./experiments/scrips/train_faster_rcnn.sh 0 pascal_voc vgg16
I have error:
lib/roi_data_layer/minibatch.py
assert(cfg.TRAIN.BATCH_SIZE % num_images ==0)
ZeroDivisionError: integer division or modulo by zero

it seems that num_images == 0 after training iter: 20/70000

so any idea?

**Comment by endernewton** [comment]
your validation roidb is empty?

**Comment by huanhuanxuxu** [comment]
hi endernewton thanks very much for the coding, very nice job. For the error, I found it also existed in original Ross Caffe realization, simple solution is to "delete cache file in VOCdevkit" each time, then everything is fine.

**Comment by endernewton** [comment]
thanks @huanhuanxuxu

**Comment by steward1212** [comment]
hi @huanhuanxuxu I encounter the same problem. You say that the solution is to "delete cache file in VOCdevkit" each time.
What do you mean delete cache file each time? Do you mean that delete file every time before training process? Or delete file in every training iteration. Thanks.

**Comment by JaylinZheng** [comment]
hi, the same problem occured. And I also delete cache file, but it doesn't work.
What can I do for solving this? Thanks very much!

**Comment by huanhuanxuxu** [comment]
Maybe you can try to delete the cache files in data/cache/ folder and try again

**Comment by JaylinZheng** [comment]
I  delete .pkl file, but the error still exist.

**Comment by tellaShoker** [comment]
@JaylinZheng Have you solve this issue? the same problem occured on me....

**Comment by FreudDolce** [comment]
The same problem occured on me

**Comment by dmerrick520** [comment]
@Hsy1996 Hi, what did you change in the pascal_voc.py file? I corrected all classes for my data set but problem persists. Any advice? 

Thank you

**Comment by BlueWings8** [comment]
@dmerrick520  the same problem occurred on me  Do you solve it? Any advice plz.

**Comment by zyuerugou** [comment]
> I have fixed it ,
> 
> def get_roidb(imdb_name):
> imdb = get_imdb(imdb_name)
> print('Loaded dataset `{:s}` for training'.format(imdb.name))
> imdb.set_proposal_method(cfg.TRAIN.PROPOSAL_METHOD)
> print('Set proposal method: {:s}'.format(cfg.TRAIN.PROPOSAL_METHOD))
> roidb = get_training_roidb(imdb)
> return roidb
> 
> I found on this function when imdb.name == test
> the len(roidb) == 0
> may when you make your own data ,you have not the test

Hello, the same problem occurred on me.
But I'm sure that I have the test.txt in the folder data/VOCdevkit/VOC2007/ImageSets/Main/, and also have the Annotations and JPEGImages. Any advice?

Thank you

**Comment by saudpp** [comment]
@BlueWings8 in which file did you fixed?

**Comment by zyuerugou** [comment]
> @BlueWings8 in which file did you fixed?

In tools/trainval_net.py
But I have the datasets for trainning and testing.
So my problem have not been solved.

**Comment by zyuerugou** [comment]
@saudpp 
In tf-faster-rcnn-master/lib/model/train_val.py
	def train_net(...):
call
	roidb = filter_roidb(roidb)
	valroidb = filter_roidb(valroidb)
	
def filter_roidb(roidb):
  """Remove roidb entries that have no usable RoIs."""

  def is_valid(entry):
    # Valid images have:
    #   (1) At least one foreground RoI OR
    #   (2) At least one background RoI
    overlaps = entry['max_overlaps']
    # find boxes with sufficient overlap
    fg_inds = np.where(overlaps >= cfg.TRAIN.FG_THRESH)[0]
    # Select background RoIs as those within [BG_THRESH_LO, BG_THRESH_HI)
    bg_inds = np.where((overlaps < cfg.TRAIN.BG_THRESH_HI) &
                       (overlaps >= cfg.TRAIN.BG_THRESH_LO))[0]
    # image is only valid if such boxes exist
    valid = len(fg_inds) > 0 or len(bg_inds) > 0
    return valid

  num = len(roidb)
  filtered_roidb = [entry for entry in roidb if is_valid(entry)]
  num_after = len(filtered_roidb)
  print('Filtered {} roidb entries: {} -> {}'.format(num - num_after,
                                                     num, num_after))
  return filtered_roidb


solved：
  tf-faster-rcnn-master/lib/datasets/pascal_voc.py
    def _load_pascal_annotation(self, index):
      # ---------------------------------------
      # user added
      #----------------------------------------
      cls_objs = [obj for obj in objs if obj.find('name').text.lower() in self._classes]
      objs = cls_objs
      print('Class: ')
      print(objs)
      #----------------------------------------
  
cls_objs = [obj for obj in objs if obj.find('name').text.lower() in self._classes]
   Before I have not added .lower()
   But in my datasets, the classname is like 'Car', and in Class pascal_voc, self._classes = ('__background__', 'car',...), the classname is like'car'.
  So my problem solved by the classname.lower()

**Comment by 407841385** [comment]
Above solution could not work, I debug myself, and found:
in layer.py  function _get_next_minibatch_inds

db_inds may be empty ,because self._cur is out of range.
so add following code before return:
    if self._cur == self._perm.size:    
      self._cur = 0

Works!

**Comment by riqsebastian** [comment]
I solve the problem by comment the 'use_diff' in the pascal_voc.py or your_database.py. If your dataset are not using difficult samples , you have to comment these lines, otherwise your dataset will be filtered to zero. It will cause your num_images become zero. FYI, If you need some ADAS dataset, please download creda open dataset on [https://www.aicreda.com/](url). Thank you.

```
        #if not self.config['use_diff']:
        #    # Exclude the samples labeled as difficult
        #    non_diff_objs = [
        #        obj for obj in objs if int(obj.find('difficult').text) == 0]
        #     if len(non_diff_objs) != len(objs):
        #         print 'Removed {} difficult objects'.format(
        #             len(objs) - len(non_diff_objs))
        #    objs = non_diff_objs
```
