### ISSUE TITLE
shape issues in rpn_bbox_pred, bbox_pred in resnet50 & coco_2014

### ISSUE THREAD

**Issue by dattranx105** [endernewton/tf-faster-rcnn#164]
with anchor_scales=[8, 16, 32], i have error 
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [48] rhs shape= [60]
	 [[Node: save/Assign_269 = Assign[T=DT_FLOAT, _class=["loc:@resnet_v1_50/rpn_bbox_pred/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](resnet_v1_50/rpn_bbox_pred/biases, save/RestoreV2_269)]]
after that, i change anchor_scales to [2, 4, 8, 16, 32] to fit rpn_bbox_pred shape to [60], i have another error in bbox_pred
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [2048,84] rhs shape= [2048,324]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@resnet_v1_50/bbox_pred/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](resnet_v1_50/bbox_pred/weights, save/RestoreV2_1)]]
How to solve it? Thank you!

**Comment by endernewton** [comment]
you are using coco models instead of voc ones somewhere?

-Xinlei

**Comment by dattranx105** [comment]
i only use demo.py. it works well with voc, but i change to coco with resnet50 or resnet101 it leads to problems

**Comment by endernewton** [comment]
demo works with voc. you may want to change some code to make it work on
coco

-Xinlei

**Comment by dattranx105** [comment]
thank you, but where i need to change to work with resnet50?
