### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by liangzeyu000** [endernewton/tf-faster-rcnn#171]
I am a tensorflow noob. When I run "./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc vgg16", some issues occurs, just like below:
----------------------------------------------------------------------------------------------------------------------------
Writing mine VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "/media/tf/MyFiles/codes/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 126, in voc_eval
    recs = pickle.load(f)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test_net.py", line 120, in <module>
    test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
  File "/media/tf/MyFiles/codes/tf-faster-rcnn/tools/../lib/model/test.py", line 193, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/media/tf/MyFiles/codes/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 287, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/media/tf/MyFiles/codes/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 250, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/media/tf/MyFiles/codes/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 128, in voc_eval
    recs = pickle.load(f, encoding='bytes')
EOFError: Ran out of input
Command exited with non-zero status 1
7.86user 0.96system 0:09.05elapsed 97%CPU (0avgtext+0avgdata 1956200maxresident)k
0inputs+56outputs (0major+355880minor)pagefaults 0swaps
-----------------------------------------------------------------------------------------------------------------------------
I need help,and is there anyone can give me some solutions?Thanks a lot!

**Comment by sheirving** [comment]
I have the same question with you.Have you solved it?

**Comment by liangzeyu000** [comment]
@sheirving sorry,I have not solved this problem yet.

**Comment by endernewton** [comment]
it has something to do with the pickle package according to the msg, can you check your installation and paths? maybe try logout and login again

**Comment by liangzeyu000** [comment]
OK,let me have a try,thank you very much!

**Comment by liangzeyu000** [comment]
OK,let me have a try, thank you very much! @endernewton

**Comment by sheirving** [comment]
@liangzeyu000   Yes! I have solved it, which troubled me for two days."Ran out of input" which is caused by the  pickle.load(f)  file is a empty file.(https://stackoverflow.com/questions/24791987/why-do-i-get-pickle-eoferror-ran-out-of-input-reading-an-empty-file).In other words ,you should see the"..../data/VOCdevkit2007/annotations_cache/.." , in which there have a '.pkl' binary file and it isn't empty. And my demo about f-rcnn is cloned from CharlesShang/TFFRCNN ,which is in python 2 . my python is 3(most questions is causd by py2 - py3), which is important,so in the'voc_eval.py'  `# save
    print('Saving cached annotations to {:s}'.format(cachefile))
    with open(cachefile, 'w') as f:
pickle.dump(recs, f)` 
should be changed  to `with open(cachefile,'wb') as f`!

**Comment by sheirving** [comment]
the '.pkl' file is 'imagesetfile_annots.pkl' . I changed ` cachefile = os.path.join(cachedir, '%s_annots.pkl' % imagesetfile)` to 'cachefile = os.path.join(cachedir, ('%s_annots.pkl' % 'imagesetfile'))'. You see if you need this step.

**Comment by endernewton** [comment]
@sheirving glad you figured it out. i have changed the cachefile path so that the model can be tested on not only the test set.

**Comment by a3551571** [comment]
@sheirving @endernewton 
excuse me.I follow your step 

# save print('Saving cached annotations to {:s}'.format(cachefile)) with open(cachefile, 'w') as f: pickle.dump(recs, f)
 change to 
with open(cachefile,'wb') as f!

But it still print:"ran out of input."
Could you show me how to solve it?Thanks a lot!

**Comment by liangzeyu000** [comment]
Thanks a lot! @sheirving @endernewton When I checked my own voc2007 dataset once again,I found a problem with xml files in the 'Annotation' directory. I found the value of boundbox in some xml files is 0. I chanded 0 to 1, then this problem was solved. 
The above is my solution.Thanks everyone.

**Comment by ReBoRn8888** [comment]
@a3551571 
I have met the same problem as yours and I have solved it.
Here's the problem:
    `cachefile = os.path.join(cachedir, '%s_annots.pkl' % imagesetfile`
    in lib/datasets/voc_eval.py line 105, 
where the variable 'imagesetfile' is 'tf-faster-rcnn/data/VOCdevkit2007/VOC2007/ImageSets/Main/test.txt', so that the variable 'cachefile' will become 'tf-faster-rcnn/data/VOCdevkit2007/VOC2007/ImageSets/Main/test.txt_annots.pkl'. That's odd.
You can change the code as follows:
    `cachefile = os.path.join(cachedir, '%s_annots.pkl' % imagesetfile.split("/")[-1].split(".")[0])`
    in lib/datasets/voc_eval.py line 105,
and the problem will be solved.

**Comment by Po-Hsuan-Huang** [comment]
The correct route should be tf-faster-rcnn/data/VOCdevkit2007/annotations_cache, but the annots.pkl is stored in tf-faster-rcnn/data/VOCdevkit2007/VOC2007/ImageSets/Main/test.txt



In pascal_voc.py  line 221:232, remove 'ImageSets', 'Main' 


    def _do_python_eval(self, output_dir='output'):
    annopath = os.path.join(
      self._devkit_path,
      'VOC' + self._year,
      'Annotations',
      '{:s}.xml')
    imagesetfile = os.path.join(
      self._devkit_path,
      'VOC' + self._year,
      'ImageSets',
      'Main',
      self._image_set + '.txt')


in lib/datasets/voc_eval.py line 105, change the code as follows:
    cachefile = os.path.join(cachedir, '%s_annots.pkl' % imagesetfile.split(".")[0])

**Comment by whuhit** [comment]
@ReBoRn8888 thank you very much

**Comment by DeepPower** [comment]
@ReBoRn8888 @sheirving Thank both of you.

**Comment by 0fine0** [comment]
@ReBoRn8888  Thanks a lot

**Comment by purbayankar** [comment]
I have tried this one https://drive.google.com/drive/folders/1QA8sAw49DJiMHF-Cr7q0j7KgKjlJyklV. These are the checkpoints for 1% labelled data provided in your repository.
