### ISSUE TITLE
undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by yfnn** [endernewton/tf-faster-rcnn#172]
when I run ./tools/demo.py, if I use the commad 'CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py', there will be error as follows:
 Traceback (most recent call last):
  File "./tools/demo.py", line 24, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
then, I go into the directory tools, and run 'python demo.py', there will be error as follows:
Traceback (most recent call last):
  File "demo.py", line 20, in <module>
    from model.test import im_detect
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/model/test.py", line 20, in <module>
    from utils.cython_nms import nms, nms_new
ImportError: /home/yangfan/tf-faster-rcnn/tools/../lib/utils/cython_nms.so: undefined symbol: _Py_ZeroStruct

So, anybody encountered this error? How could I fix it?

**Comment by shengcheng** [comment]
Check Makefile to make sure you use the correct version of python. [rbgirshick/py-faster-rcnn#503](url)

**Comment by zhimengfan1990** [comment]
as shengcheng said, if you are using python3, replace python with python3 in lib/Makefile

**Comment by endernewton** [comment]
thanks @shengcheng @zhimengfan1990!
