### ISSUE TITLE
What Kind  of GPU models to be used ?

### ISSUE THREAD

**Issue by satya2550** [endernewton/tf-faster-rcnn#174]
apart from tested GPU models TitanX (Maxwell/Pascal),Grid K520 (AWS g2.2xlarge) and Tesla K80 (AWS p2.xlarge)

**Comment by endernewton** [comment]
don't know exactly what you mean.. but it should support major gpu types

**Comment by satya2550** [comment]
Can you recommend some other GPU models other than  TitanX (Maxwell/Pascal),Grid K520 (AWS g2.2xlarge) and Tesla K80 (AWS p2.xlarge).

**Comment by endernewton** [comment]
many can be tried, for example 1080..
