### ISSUE TITLE
How to get the recall rate with respect to precision?

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#175]
I have performed the faster rcnn on a dataset and gotten the average precision (**AR**) results as they can be seen at the end of testing. But at the end of this repository (description page) it can be seen that the average recall (**AR**) rates are also calculated. How can I get the recall rate with respect to each precision to draw a chart like below?
![untitled](https://user-images.githubusercontent.com/24352869/28871905-f1d7e6c6-779b-11e7-9b6a-224935af02b9.gif)

**Comment by endernewton** [comment]
or this is just precision changes as examples kick in, there are many code for this, for example in voc

**Comment by hadi-ghnd** [comment]
So you mean that I should write a code to draw the precision-recall curve at the end of **test_faster_rcnn.sh**? How did you get the **AR** (average recall) values [here](https://github.com/endernewton/tf-faster-rcnn#detailed-numbers-from-coco-server)?

**Comment by endernewton** [comment]
you can use https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/datasets/voc_eval.py.
