### ISSUE TITLE
about "Build the Cython modules" problem

### ISSUE THREAD

**Issue by a3551571** [endernewton/tf-faster-rcnn#176]
Hello dear guys,I met a problem when I run the code.
At "Build the Cython modules" step,I input 'make',but it print "warning" like this:

python setup.py build_ext --inplace
running build_ext
cythoning utils/bbox.pyx to utils/bbox.c
building 'utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/utils
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wzx/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/wzx/anaconda3/include/python3.5m -c utils/bbox.c -o build/temp.linux-x86_64-3.5/utils/bbox.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -L/home/wzx/anaconda3/lib -Wl,-rpath=/home/wzx/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/utils/bbox.o -L/home/wzx/anaconda3/lib -lpython3.5m -o /home/wzx/chris/spider_man/com/tf-faster-rcnn-r1.0/lib/utils/cython_bbox.cpython-35m-x86_64-linux-gnu.so
cythoning utils/nms.pyx to utils/nms.c
building 'utils.cython_nms' extension
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wzx/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/wzx/anaconda3/include/python3.5m -c utils/nms.c -o build/temp.linux-x86_64-3.5/utils/nms.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -L/home/wzx/anaconda3/lib -Wl,-rpath=/home/wzx/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/utils/nms.o -L/home/wzx/anaconda3/lib -lpython3.5m -o /home/wzx/chris/spider_man/com/tf-faster-rcnn-r1.0/lib/utils/cython_nms.cpython-35m-x86_64-linux-gnu.so
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
building 'nms.cpu_nms' extension
creating build/temp.linux-x86_64-3.5/nms
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wzx/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/wzx/anaconda3/include/python3.5m -c nms/cpu_nms.c -o build/temp.linux-x86_64-3.5/nms/cpu_nms.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -L/home/wzx/anaconda3/lib -Wl,-rpath=/home/wzx/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/nms/cpu_nms.o -L/home/wzx/anaconda3/lib -lpython3.5m -o /home/wzx/chris/spider_man/com/tf-faster-rcnn-r1.0/lib/nms/cpu_nms.cpython-35m-x86_64-linux-gnu.so
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
building 'nms.gpu_nms' extension
{'nvcc': ['-arch=sm_52', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"], 'gcc': ['-Wno-unused-function']}
/usr/local/cuda/bin/nvcc -I/home/wzx/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/usr/local/cuda/include -I/home/wzx/anaconda3/include/python3.5m -c nms/nms_kernel.cu -o build/temp.linux-x86_64-3.5/nms/nms_kernel.o -arch=sm_52 --ptxas-options=-v -c --compiler-options '-fPIC'
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z10nms_kernelifPKfPy' for 'sm_52'
ptxas info    : Function properties for _Z10nms_kernelifPKfPy
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 22 registers, 1280 bytes smem, 344 bytes cmem[0], 12 bytes cmem[2]
{'nvcc': ['-arch=sm_52', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"], 'gcc': ['-Wno-unused-function']}
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wzx/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/usr/local/cuda/include -I/home/wzx/anaconda3/include/python3.5m -c nms/gpu_nms.cpp -o build/temp.linux-x86_64-3.5/nms/gpu_nms.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/wzx/anaconda3/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /home/wzx/anaconda3/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/wzx/anaconda3/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from nms/gpu_nms.cpp:346:
/home/wzx/anaconda3/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
g++ -pthread -shared -L/home/wzx/anaconda3/lib -Wl,-rpath=/home/wzx/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/nms/nms_kernel.o build/temp.linux-x86_64-3.5/nms/gpu_nms.o -L/usr/local/cuda/lib64 -L/home/wzx/anaconda3/lib -Wl,--enable-new-dtags,-R/usr/local/cuda/lib64 -lcudart -lpython3.5m -o /home/wzx/chris/spider_man/com/tf-faster-rcnn-r1.0/lib/nms/gpu_nms.cpython-35m-x86_64-linux-gnu.so

Did anyone meet the same problem?
Thanks!

**Comment by engineer1109** [comment]
warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
this warning alse happened to me

**Comment by engineer1109** [comment]
You may refer to it.
https://github.com/endernewton/tf-faster-rcnn/issues/198

**Comment by endernewton** [comment]
thanks @engineer1109!
