### ISSUE TITLE
is it easy to add a mask brach to the current code? 

### ISSUE THREAD

**Issue by Jiakui** [endernewton/tf-faster-rcnn#179]
Hi , I would like to implement mask rcnn based on this project. Can anybody give me some hint ?  

Thanks

**Comment by philokey** [comment]
You can refer to [this project](https://github.com/CharlesShang/FastMaskRCNN)

**Comment by endernewton** [comment]
let me know how it goes! if you decide to do mask rcnn with the current repo, i am happy to discuss possible issues you may encounter
