### ISSUE TITLE
Is weighted classes supported?

### ISSUE THREAD

**Issue by gary-jiao** [endernewton/tf-faster-rcnn#181]
Currently, I am training the data with imbalanced classes, such as class A 80% and class B 20%. And got terrible result as class B cannot be classified correctly. In most images, just class A could be recognized and seems class B has been ignored.
I made the research and found that this kind of situation could be solved with weighted classes. However, I am not sure if this framework have already included this feature? If so, could you tell me how to configure it? Thank you.

**Comment by endernewton** [comment]
you can just do weighted sampling instead of pure weighting. this is the easiest change with the current repo in my mind. you can start with the roi data layers.
