### ISSUE TITLE
Lower AP on COCO

### ISSUE THREAD

**Issue by hqqxyy** [endernewton/tf-faster-rcnn#183]
Hi,

I try to retrain res101 on COCO dataset. But I can not get the same result in the report(32.2 for 1190k iter, 31.1 for 490k iter, 34.1 in the report), But I can get the same result using provided models. 

I am using tf 1.2. Is it a same bug in https://github.com/endernewton/tf-faster-rcnn/issues/42 ?

Thanks!

**Comment by endernewton** [comment]
interesting. which commit do you use? the #42 is fixed.

**Comment by hqqxyy** [comment]
I am using the newest version.

**Comment by endernewton** [comment]
just did couple of changes in the past few days, u mean e533d5a?

**Comment by hqqxyy** [comment]
ooh, I used this commit 

247c38d5dd17c95bb3036fcc6a569f108f8c4cb3

**Comment by endernewton** [comment]
did you find anything interesting? i just did some training and it seems fine to me, at least on voc.

**Comment by hqqxyy** [comment]
Hi, I have retrained res101 and vgg16 on VOC2007 and VOC0712. On VOC2007, the mAP is lower too. So, maybe there is something wrong with data pre-process on VOC2007 and COCO

For res101 on VOC2007, the mAP is 73.6, compared to 75.2 in the report.

For vgg16 on VOC2007, the mAP is 70.2, compared to 71.2 in the report.

But for vgg16 on VOC0712, the mAP is 75.5, compared to 75.3 in the report.

For res101 on VOC0712, the mAP is 79.0, compared to 79.3 in the report.

**Comment by endernewton** [comment]
Did you test with nms mode? The numbers look fine to me, but I can check if there is anything suspicious in the latest code.

**Comment by ppwwyyxx** [comment]
Running `./experiments/scripts/train_faster_rcnn.sh 0 coco res50 ` with the code unmodified only gives me 28.6 mAP.

**Comment by endernewton** [comment]
@ppwwyyxx how many iterations do you run? 28.6 seems good to me if you run only 490k iterations. Also the code is recently updated, should give around 29.3 now.

**Comment by ppwwyyxx** [comment]
Yes I'm using the default (490k). Could you provide a config with better performance?

**Comment by endernewton** [comment]
just change 350k/490k to 900k/1190k. should give that.

-Xinlei

**Comment by ppwwyyxx** [comment]
Ah! I didn't know the "(900k/1190k)" in README is the number of iterations! Thx

**Comment by endernewton** [comment]
sure! i should probably update my readme then. closing this.

**Comment by ppwwyyxx** [comment]
Running ` ./experiments/scripts/train_faster_rcnn.sh 0 coco res50` on commit becb347c4dd9dfef206b4c5659c31f9c4e with the following modification:
```diff
diff --git i/experiments/scripts/test_faster_rcnn.sh w/experiments/scripts/test_faster_rcnn.sh
index 7d288c7..6a2367f 100755
--- i/experiments/scripts/test_faster_rcnn.sh
+++ w/experiments/scripts/test_faster_rcnn.sh
@@ -32,7 +32,7 @@ case ${DATASET} in
   coco)
     TRAIN_IMDB="coco_2014_train+coco_2014_valminusminival"
     TEST_IMDB="coco_2014_minival"
-    ITERS=490000
+    ITERS=1190000
     ANCHORS="[4,8,16,32]"
     RATIOS="[0.5,1,2]"
     ;;
diff --git i/experiments/scripts/train_faster_rcnn.sh w/experiments/scripts/train_faster_rcnn.sh
index d5de07c..fe4df25 100755
--- i/experiments/scripts/train_faster_rcnn.sh
+++ w/experiments/scripts/train_faster_rcnn.sh
@@ -34,8 +34,8 @@ case ${DATASET} in
   coco)
     TRAIN_IMDB="coco_2014_train+coco_2014_valminusminival"
     TEST_IMDB="coco_2014_minival"
-    STEPSIZE="[350000]"
-    ITERS=490000
+    STEPSIZE="[900000]"
+    ITERS=1190000
     ANCHORS="[4,8,16,32]"
     RATIOS="[0.5,1,2]"
     ;;
```
gives me 30.3 mAP.

**Comment by endernewton** [comment]
interesting, so what is the performance you get when setting it to
350k/490k? what is the performance on voc? also can you share the model you
trained? i can try to train on my side again as well, but since i just
trained the models two weeks back it is surprising to see this difference.

-Xinlei

**Comment by ppwwyyxx** [comment]
Ah. Looking at the log closer, I found that the script automatically picks up the old 490k model (trained with an earlier version of the code) and continue from it. Maybe this can cause some problems. I don't have any other numbers for the moment. I'll try again if I have time. Thanks a lot!

**Comment by endernewton** [comment]
Thanks! Let me know if you things go wrong again. :)

-Xinlei
