### ISSUE TITLE
why the training speed is faster and faster?

### ISSUE THREAD

**Issue by yaoqi-zd** [endernewton/tf-faster-rcnn#185]
I'm training faster rcnn with vgg16 backbone on Pascal VOC 2007 following the instruction
`./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc vgg16`

My environment is Ubuntu14.04 + Tensorflow r1.2 + GTX1080ti, The elapse time for each iteration is decaying during my training procedure, the speed goes from ~1.4s/iter to ~0.4s/iter, I'm just curious why this happens?

**Comment by endernewton** [comment]
tensorflow gets warmed up.. in the first few iterations it is quite slow for some reason, but in the end it converges to its normal speed
