### ISSUE TITLE
Couldn't reach claimed mAP result?

### ISSUE THREAD

**Issue by TheodoreG** [endernewton/tf-faster-rcnn#188]
Dear Author, I have trained two models based on vgg16 and res101 and pascal_voc 2007 dataset. I just used your original code without any modification. But I only got mAP 62.3 for vgg16 and 67.1 for res101, which has a 10 point decrease compared to your claimed result. My gpu is Tesla K40m.

**Comment by endernewton** [comment]
check your nms compilation? also can you do test on the released model?

**Comment by TheodoreG** [comment]
After I have changed the architecture from sm_52 to sm_30 and the pre-trained model for pascal_voc_0712 and res101 setting I have got the 78.7 mAP. Thank you so much for your indication!

**Comment by endernewton** [comment]
cool
