### ISSUE TITLE
Run demo.py error

### ISSUE THREAD

**Issue by hellozgm** [endernewton/tf-faster-rcnn#189]
Hi, sorry to bother you, but when I run the ./tools/demo.py code. It throws out an error:

Traceback (most recent call last):
  File "./tools/demo.py", line 142, in <module>
    tag='default', anchor_scales=[8, 16, 32])
TypeError: create_architecture() got multiple values for keyword argument 'tag'

I couldn't find where is wrong. My environment is Ubuntu16.04 + tensorflow r1.2 + GPU is laptop one(GTX850m).

**Comment by endernewton** [comment]
should be fixed now. sorry i did some change in the code recently and didn't pay attention to the demo. closing.
