### ISSUE TITLE
Assertion error while trying to add bounding box rotation

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#195]
I am trying to add data augmentation (rotation) to the model on a custom dataset. So far I have added this function to [imdb.py](https://github.com/endernewton/tf-faster-rcnn/blob/9336b01e5208a1640bd30fef773137c54b0c2cb9/lib/datasets/imdb.py#L125):

```
def append_rotated_images(self):
    num_images = self.num_images
    widths = self._get_widths()
    for i in range(num_images):
      boxes = self.roidb[i]['boxes'].copy()
      oldx1 = boxes[:, 0].copy()
      oldx2 = boxes[:, 2].copy()
	  oldy1 = boxes[:, 1].copy()
      oldy2 = boxes[:, 3].copy()
	  
	  dx = oldx2-oldx1
	  dy = oldy2-oldy1
	  
	  xc = oldx2 - dx/2
	  yc = oldy2 - dy/2
	  	   
      boxes[:, 0] = xc - (dy/2) - 1
      boxes[:, 2] = xc + (dy/2) - 1
      boxes[:, 1] = yc - (dx/2) - 1
      boxes[:, 3] = yc + (dx/2) - 1
	  
      assert (boxes[:, 2] >= boxes[:, 0] and boxes[:, 3] >= boxes[:, 1]).all()
      entry = {'boxes': boxes,
               'gt_overlaps': self.roidb[i]['gt_overlaps'],
               'gt_classes': self.roidb[i]['gt_classes'],
               'rotated': True}
      self.roidb.append(entry)
    self._image_index = self._image_index * 4
```

and added this to [minibatch.py](https://github.com/endernewton/tf-faster-rcnn/blob/9336b01e5208a1640bd30fef773137c54b0c2cb9/lib/roi_data_layer/minibatch.py#L54):

```
if roidb[i]['rotated']:
	  rotation_matrix = cv2.getRotationMatrix2D((num_cols/2, num_rows/2), 90, 1)
	  img_rotation = cv2.warpAffine(im, rotation_matrix, (num_cols, num_rows))
	  #im = im.rotate(im, 90)
```
But now I get the assertion error about `assert (boxes[:, 2] >= boxes[:, 0]).all()`. I think it's because the images don't rotate properly in **minibatch.py**. I don't know exactly how to rotate images in python.

How can I rotate each image by 90 degrees anticlockwise?

**Comment by endernewton** [comment]
if you have a fixed set of degrees to rotate, just rotate them first, and then create an augmented roidb.
