### ISSUE TITLE
Running Wrong with the gpu_nms

### ISSUE THREAD

**Issue by engineer1109** [endernewton/tf-faster-rcnn#198]
when running with the cpu_nms.so, everything works well.
when running with the gpu_nms.so,   the nms don't work at all.

When compiling the gpu_nms, the warning reports,

{'gcc': ['-Wno-unused-function'], 'nvcc': ['-arch=sm_52', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"]}
/usr/local/cuda-8.0/bin/nvcc -I/home/rfcn/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-8.0/include -I/home/rfcn/anaconda2/include/python2.7 -c nms/nms_kernel.cu -o build/temp.linux-x86_64-2.7/nms/nms_kernel.o -arch=sm_52 --ptxas-options=-v -c --compiler-options '-fPIC'
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z10nms_kernelifPKfPy' for 'sm_52'
ptxas info    : Function properties for _Z10nms_kernelifPKfPy
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 22 registers, 1280 bytes smem, 344 bytes cmem[0], 12 bytes cmem[2]
{'gcc': ['-Wno-unused-function'], 'nvcc': ['-arch=sm_52', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"]}
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rfcn/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-8.0/include -I/home/rfcn/anaconda2/include/python2.7 -c nms/gpu_nms.cpp -o build/temp.linux-x86_64-2.7/nms/gpu_nms.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/rfcn/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /home/rfcn/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/rfcn/.local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from nms/gpu_nms.cpp:346:
/home/rfcn/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
g++ -pthread -shared -L/home/rfcn/anaconda2/lib -Wl,-rpath=/home/rfcn/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/nms/nms_kernel.o build/temp.linux-x86_64-2.7/nms/gpu_nms.o -L/usr/local/cuda-8.0/lib64 -L/home/rfcn/anaconda2/lib -Wl,-R/usr/local/cuda-8.0/lib64 -lcudart -lpython2.7 -o /home/rfcn/tf-rfcn/lib/nms/gpu_nms.so
rm -rf build

My Cuda is 8.0, Cudnn 6.0     using python 2.7 and ubuntu 16.04.
What may cause it

**Comment by JRCondeNast** [comment]
Have you double check which GPU you use and the corresponding Archetecture of the GPU? If you use Pascal Architecture like GTX1080Ti/ GTX 1080, you need to change the -arch=sm_61 in setup.py in lib.

**Comment by engineer1109** [comment]
@JRCondeNast My GPU is Nvidia GTX960M      is it sm_61?

**Comment by supertuzi** [comment]
If I understand correctly both sm_50 and sm_61 should work for GTX960M. But it may influence the speed. I would say give it a try and let us know.

**Comment by engineer1109** [comment]
@supertuzi   Very thanks to you,  sm_61 don't work for Nvidia GTX960M,but sm_50 works well for Nvidia GTX690M. My GPU_NMS looks work well now.
Moreover, do you know how to find what sm_xx is suitable for the gpu?  I have another server using Tesla GPU.

**Comment by JRCondeNast** [comment]
@endernewton mentioned somthing here.
TitanX (Maxwell/Pascal) | sm_52
Grid K520 (AWS g2.2xlarge) | sm_30
Tesla K80 (AWS p2.xlarge) | sm_37
 I have additional information: GTX1080Ti|sm_61 and GTX_1080| sm_61.

**Comment by JRCondeNast** [comment]
Sorry I'm kinda of switching between my two Github accounts. Hope those helpful.

**Comment by endernewton** [comment]
thanks @JRCondeNast i am updating it.

**Comment by wudi00** [comment]
@JRCondeNast My gpu is  GTX 1080, I changed the  -arch=sm_61 in setup.py, but still, the question remains. 
`building 'nms.gpu_nms' extension
{'gcc': ['-Wno-unused-function'], 'nvcc': ['-arch=sm_61', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"]}
/usr/local/cuda/bin/nvcc -I/media/disk/wudi/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/local/cuda/include -I/opt/anaconda3/envs/py36/include/python3.6m -c nms/nms_kernel.cu -o build/temp.linux-x86_64-3.6/nms/nms_kernel.o -arch=sm_61 --ptxas-options=-v -c --compiler-options '-fPIC'
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z10nms_kernelifPKfPy' for 'sm_61'
ptxas info    : Function properties for _Z10nms_kernelifPKfPy
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 25 registers, 1280 bytes smem, 344 bytes cmem[0], 12 bytes cmem[2]
{'gcc': ['-Wno-unused-function'], 'nvcc': ['-arch=sm_61', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"]}
gcc -pthread -B /opt/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/media/disk/wudi/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/local/cuda/include -I/opt/anaconda3/envs/py36/include/python3.6m -c nms/gpu_nms.cpp -o build/temp.linux-x86_64-3.6/nms/gpu_nms.o -Wno-unused-function
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /media/disk/wudi/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                 from /media/disk/wudi/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /media/disk/wudi/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from nms/gpu_nms.cpp:346:
`
How to solve it? Thanks

**Comment by zxGuo** [comment]
@engineer1109  Hi, have you fixed this problem? I just met with the same problem: the cpu_nms works well, but gpu_nms does not work at all. Thanks for your help!

**Comment by engineer1109** [comment]
@zxGuo  Have solved for three years.
The sm does matter with the gpu card.
The RTX 2080ti is sm_75.

**Comment by zxGuo** [comment]
@engineer1109 Unluckily changing sm does not solve my problem.
I already use sm_75 during compiling (my gpu is RTX2080 super), and I even have tried other parameters from sm_35 to sm_75, nothing works.
Do you remember that after you changed the sm_ setting, did you still get the same warning information during compiling?
Because I am getting exactly the same warning as you reported.

**Comment by Jordy-Li** [comment]
@zxGuo  Have you solve this problem?  my gpu is RTX2070 super.
