### ISSUE TITLE
Trouble downloading models

### ISSUE THREAD

**Issue by DavidSPumpkins** [endernewton/tf-faster-rcnn#2]
I'm using your script to fetch faster-rcnn models and it seems to be hanging. I'm not sure if this is due to heavy traffic or an error. Regardless, I thought I would ask if you had any suggestions. Thanks!

**Comment by endernewton** [comment]
Maybe the server is down.. let me go ahead and restart it for you.

**Comment by DavidSPumpkins** [comment]
Thanks for the quick response! I just tried again from two different systems and two different domains and the results are the same. Specifically this...

--2017-02-09 22:40:46--  (try: 3)  http://gs11655.sp.cs.cmu.edu/xinleic/tf-faster-rcnn/faster_rcnn_models.tgz
Connecting to gs11655.sp.cs.cmu.edu (gs11655.sp.cs.cmu.edu)|128.2.194.7|:80... failed: Connection timed out.
Retrying.

This goes on for 20 "tries" until it times out completely. Maybe the domain from which you are sharing the models is privileged and requires a VPN? I'm just spitballing, so this could easily be wrong. Anyway, thanks for the effort!

**Comment by endernewton** [comment]
Should be up by now. The machine is rebooted

**Comment by DavidSPumpkins** [comment]
That worked. Thanks!

**Comment by tuan3w** [comment]
Hey @endernewton,
I think the server is down again. I can't download the models. Can you restart the server again or put them in a more stable online storage?

**Comment by endernewton** [comment]
Okay I will fix it by tomorrow morning and put a backup link.

**Comment by endernewton** [comment]
Should be up now. :)
