### ISSUE TITLE
Self-defined anchor ratios

### ISSUE THREAD

**Issue by xioryu** [endernewton/tf-faster-rcnn#20]
@endernewton  The anchor ratios are hardcoded as [0.5, 1, 2] in current version and the field "num_anchors" is computed by scales.shape[0] * 3
I suppose there should be some kind of interfaces that expose the anchor_ratio field, so that users may define their own ratios for various detection tasks.

**Comment by endernewton** [comment]
i will update it in the next commit. close it for now.
