### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xzha8059** [endernewton/tf-faster-rcnn#202]
I used tensorflow 1.0 in cloud, but I had some error in the following, who can help me. Thanks

[[Node: resnet_v1_101/conv1/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](resnet_v1_101/Pad, resnet_v1_101/conv1/weights/read)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[1,300,400,64]
	 [[Node: resnet_v1_101/conv1/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](resnet_v1_101/Pad, resnet_v1_101/conv1/weights/read)]]
Traceback (most recent call last):
  File "./tools/demo.py", line 154, in <module>
    demo(sess, net, im_name)
  File "./tools/demo.py", line 86, in demo
    scores, boxes = im_detect(sess, net, im)
  File "/home2/xzha8059/tf-faster-rcnn/tools/../lib/model/test.py", line 96, in im_detect
    _, scores, bbox_pred, rois = net.test_image(sess, blobs['data'], blobs['im_info'])
  File "/home2/xzha8059/tf-faster-rcnn/tools/../lib/nets/network.py", line 362, in test_image
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,300,400,64]
	 [[Node: resnet_v1_101/conv1/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](resnet_v1_101/Pad, resnet_v1_101/conv1/weights/read)]]
	 [[Node: add/_1079 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_2294_add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by JRCondeNast** [comment]
If you clone the master branch of this repo, some of the resnet related code have already been updated to use tensorflow1.2.0. I would say either use new tensorflow or checkout a release version which use 1.0.

**Comment by xzha8059** [comment]
Thanks for your reply, I used the 1.0 branch of this repo in the cloud server. I am confused.

**Comment by JRCondeNast** [comment]
I thought you used Tensorflow 1.0 but clone the master branch instead of r1.0. Sorry for the confusion. Cause the resnet code changed from 1.0 to 1.2.

**Comment by endernewton** [comment]
thanks @JRCondeNast !
