### ISSUE TITLE
Short question about small objects

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#203]
I had a little question about this statement on the page:

> Since we keep the small proposals (< 16 pixels width/height), our performance is especially good for small objects.

How exactly is the model keeping the small proposals? Does this mean that we don't have to change the **RPN_MIN_SIZE** (which is 16 by default)?

thanks

**Comment by JRCondeNast** [comment]
I think so. If you go to lib/layer_utils/generate_anchors.py the base_size of archors is by default 16.

**Comment by hadi-ghnd** [comment]
@JRCondeNast you mean if I change the [ line 41](https://github.com/endernewton/tf-faster-rcnn/blob/9336b01e5208a1640bd30fef773137c54b0c2cb9/lib/layer_utils/generate_anchors.py#L41) below in  **lib/layer_utils/generate_anchors.py** from

```
def generate_anchors(base_size=16, ratios=[0.5, 1, 2],
                     scales=2 ** np.arange(3, 6)):
```

to:

```
def generate_anchors(base_size=2, ratios=[0.5,1,2],
                     scales=2 ** np.arange(3, 6)):
```
what exactly would change? 
Also I don't get the **np.arrange(3,6)** part. I know the default anchor sizes are **128,256,512** which come from **16 * [8,16,32]**; but what is the multiple np.arrange(3,6) for?

thanks

**Comment by JRCondeNast** [comment]
If I understand corretly: the default scales for the anchor is __C.ANCHOR_SCALES = [8,16,32]. Python's default parameter can be specified by this scales = 2**np.arrange(3,6) if you don't pass in scales yourself the default one is 2**np.arrange(3,6) = [8,16,32].

**Comment by hadi-ghnd** [comment]
@JRCondeNast I get it now. As you mentioned, the default anchor scales are [8,16,32] which are calculated from this scales=2 ** np.arange(3, 6). Although in the main article of faster rcnn it says:

> For anchors, we use 3 scales with box areas of 128**2, 256**2, and 512**2 pixels, and 3 aspect ratios of 1:1, 1:2, and 2:1.

I don't know if the [8,16,32] values are multiplied by **16** to become [128,256,512] or it's something else.
