### ISSUE TITLE
 Branch 1.0 cannot import name resnet_v1_block

### ISSUE THREAD

**Issue by ChengZY** [endernewton/tf-faster-rcnn#205]
Hi, guys, I have a problem.
I am using unbuntu14.0, python  2.7 tensorflow 1.0. When I try to train my own model, its hows 
from tensorflow.contrib.slim.python.slim.nets.resnet_v1 import resnet_v1_block
ImportError: cannot import name resnet_v1_block
I have down loaded branch r1.0, why I still have this problem Could you give me some advice?

**Comment by ChengZY** [comment]
./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc vgg16
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=0
+ DATASET=pascal_voc
+ NET=vgg16
+ array=($@)
+ len=3
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case ${DATASET} in
+ TRAIN_IMDB=voc_2007_trainval
+ TEST_IMDB=voc_2007_test
+ STEPSIZE='[50000]'
+ ITERS=70000
+ ANCHORS='[8,16,32]'
+ RATIOS='[0.5,1,2]'
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2017-08-30_20-15-09
+ exec
++ tee -a experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2017-08-30_20-15-09
+ echo Logging output to experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2017-08-30_20-15-09
Logging output to experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2017-08-30_20-15-09
+ set +x
+ '[' '!' -f output/vgg16/voc_2007_trainval/default/vgg16_faster_rcnn_iter_70000.ckpt.index ']'
+ [[ ! -z '' ]]
+ CUDA_VISIBLE_DEVICES=0
+ time python ./tools/trainval_net.py --weight data/imagenet_weights/vgg16.ckpt --imdb voc_2007_trainval --imdbval voc_2007_test --iters 70000 --cfg experiments/cfgs/vgg16.yml --net vgg16 --set ANCHOR_SCALES '[8,16,32]' ANCHOR_RATIOS '[0.5,1,2]' TRAIN.STEPSIZE '[50000]'
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 22, in <module>
    from nets.resnet_v1 import resnetv1
  File "/home/zy/DL/frcnn-py27-tf10/tf-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 16, in <module>
    from tensorflow.contrib.slim.python.slim.nets.resnet_v1 import resnet_v1_block
ImportError: cannot import name resnet_v1_block
Command exited with non-zero status 1
1.94user 2.40system 0:01.95elapsed 222%CPU (0avgtext+0avgdata 266500maxresident)k
0inputs+32outputs (0major+40277minor)pagefaults 0swaps

**Comment by JRCondeNast** [comment]
I tested with ubuntu 16.04 and python 2.7 and tensorflow-gpu=1.0.1(installed by conda) in conda environment. By open python and type the following command: 
'''Shell
(tensorflow_1_0) jiwen@bigo:~$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
>>> from tensorflow.contrib.slim.python.slim.nets.resnet_v1 import resnet_v1_block
>>> 
'''
It works.
Not a completely same environment as yours but hope this can give you some alternatives.

**Comment by endernewton** [comment]
close as of now. thanks @JRCondeNast !
