### ISSUE TITLE
How to draw the Recall-IoU curve?

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#206]
I have tried to draw the **Precision-Recall curve** in **pascal_voc.py** like below:

```
    pl.plot(rec, prec, lw=lw, label = cls)
    pl.xlabel('Recall')
    pl.ylabel('Precision')
    plt.grid(True)
    pl.ylim([0.0, 1.05])
    pl.xlim([0.0, 1.0])
    pl.title('Precision-Recall')
    pl.legend(loc="upper right")     
    plt.show()
```
This is based on [this part of the code](https://github.com/endernewton/tf-faster-rcnn/blob/9336b01e5208a1640bd30fef773137c54b0c2cb9/lib/datasets/pascal_voc.py#L242) which has the variables **rec**, **prec**, and **ap**.

How can I draw the **Recall-IoU curve** and **Recall-NumberOfProposals curve** like below? Where can I get the IoU  and Number of proposals values?

![untitled-3](https://user-images.githubusercontent.com/24352869/29855732-4d03ead6-8d63-11e7-8dda-cbac34fcf190.png)

thanks

**Comment by endernewton** [comment]
just testing with different number of proposals and  iou threshold.

**Comment by feiqinaqian** [comment]
hey bro，could you tell me how to draw the Precision-Recall curve step by step?

**Comment by feiqinaqian** [comment]
I don't know how to do it
