### ISSUE TITLE
How to visualize generated anchor boxes?

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#207]
I am trying to draw the generated anchor boxes (or a number of them, e.g. 10 anchors per image) during the anchor generation process on the image to have a better view of the anchor sizes. Is there a way to do this?
I would appreciate if more experts could help me with this. Can I add something like this to **proposal_layer.py**:

    im = im[:, :, (2, 1, 0)]
    fig, ax = plt.subplots(figsize=(12, 12))
    ax.imshow(im, aspect='equal')
    for i in inds:
        bbox = bbox_deltas[i, :4]

        ax.add_patch(
            plt.Rectangle((bbox[0], bbox[1]),
                          bbox[2] - bbox[0],
                          bbox[3] - bbox[1], fill=False,
                          edgecolor='red', linewidth=3.5)
            )

    plt.axis('off')
    plt.tight_layout()
    plt.draw()

**Comment by endernewton** [comment]
i have added a visualization code to tensorboard now. check that. closing.

**Comment by kemangjaka** [comment]
Hi, may I ask where did you add visualization code of generated anchor box?

If my understanding is correct, 
```
  def _add_gt_image_summary(self):
    # use a customized visualization function to visualize the boxes
    if self._gt_image is None:
      self._add_gt_image()
    image = tf.py_func(draw_bounding_boxes, 
                      [self._gt_image, self._gt_boxes, self._im_info],
                      tf.float32, name="gt_boxes")
    
    return tf.summary.image('GROUND_TRUTH', image)
```
at the network.py only visualizes ground truth bounding box, right?

I really appreciate you provide code!

**Comment by rnsandeep** [comment]
This library only provides visualization for ground_truth boxes, I have written my own functions to extend them to visualize target_boxes, predicted_boxes, anchor_boxes.

These are the functions.
  def get_boxes(self, name, phase):
     if phase == 'pred':
        bbox_pred = self._predictions['bbox_pred']
        rois = self._predictions['rois']
        im_scales = tf.py_func(get_imscale,[self._im_info], tf.float32)
        boxes = rois[:, 1:5] / im_scales[0]
        bbox_pred = tf.reshape(bbox_pred, [bbox_pred.shape[0], -1])
        box_deltas = bbox_pred
        if name == 'bbox':
            pred_boxes = bbox_transform_inv_tf(boxes, box_deltas)
            final_boxes = clip_boxes_tf(pred_boxes, self._im_info)
        else:
            final_boxes = clip_boxes_tf(boxes, self._im_info)
     else:
        bbox_targets = self._proposal_targets['bbox_targets']
        rois = self._proposal_targets['rois']
        im_scales = tf.py_func(get_imscale,[self._im_info], tf.float32)
        boxes = rois[:, 1:5] / im_scales[0]
        bbox_targets = tf.reshape(bbox_targets, [bbox_targets.shape[0], -1])
        box_deltas = bbox_targets
        if name == 'bbox':
            target_boxes = bbox_transform_inv_tf(boxes, box_deltas)
            final_boxes = clip_boxes_tf(target_boxes, self._im_info)
        else:
            final_boxes = clip_boxes_tf(boxes, self._im_info)

     return final_boxes

  def _add_target_image_summary(self):
    if self._gt_image is None:
      self._add_gt_image()

    target_boxes = self.get_boxes('bbox', 'target')
#    target_boxes = tf.py_func(getIndexes,
#                      [target_boxes, self._proposal_targets["labels"],'bbox'],
#                      tf.float32, name="getindexes")
    boxes = tf.concat([target_boxes,tf.cast(self._proposal_targets["labels"], tf.float32)],1)
    target_image = tf.py_func(draw_bounding_boxes,
                      [self._gt_image, boxes, self._im_info, "bbox_targets"],
                      tf.float32, name="bbox_targets")
    return tf.summary.image('2_BBOX_TARGETS', target_image), target_image

  def _add_anchor_target_image_summary(self):
    if self._gt_image is None:
      self._add_gt_image()
    anchors = self._anchor_targets['anchor_targets']
    label = tf.py_func(getShape,
                      [anchors],
                      tf.float32, name="getShape")
    boxes = tf.concat([anchors, label],1)
    anchor_target_image = tf.py_func(draw_bounding_boxes,
                      [self._gt_image, boxes, self._im_info, "anchor_targets"],
                      tf.float32, name="anchor_targets")
    return tf.summary.image('3_ANCHOR_TARGETS', anchor_target_image), anchor_target_image

  def _add_pred_image_summary(self):
    if self._gt_image is None:
      self._add_gt_image()
    pred_boxes = self.get_boxes('bbox', 'pred')
#    pred_boxes = tf.py_func(getIndexes,
#                      [pred_boxes, self._proposal_targets["labels"],'bbox'],
#                      tf.float32, name="indexes")
    boxes = tf.concat([pred_boxes,tf.cast(self._proposal_targets["labels"], tf.float32)],1)
    pred_image = tf.py_func(draw_bounding_boxes,
                      [self._gt_image, boxes, self._im_info, "bbox_pred"],
                      tf.float32, name="bbox_pred")
    return tf.summary.image('4_BBOX_PREDICTIONS', pred_image), pred_image

  def _add_rois_pred_image_summary(self):
    if self._gt_image is None:
      self._add_gt_image()
    rois_pred_boxes = self.get_boxes('rois','pred')
    boxes = tf.concat([rois_pred_boxes,tf.cast(self._proposal_targets["labels"], tf.float32)],1)
    rois_pred_image = tf.py_func(draw_bounding_boxes,
                      [self._gt_image, boxes, self._im_info, "rois_predictions"],
                      tf.float32, name="rois_predictions")
    return tf.summary.image('3_ROIS_PREDICTIONS', rois_pred_image), rois_pred_image

  def _add_rois_target_image_summary(self):
    if self._gt_image is None:
      self._add_gt_image()
    rois_target_boxes = self.get_boxes('rois','target')
    boxes = tf.concat([rois_target_boxes,tf.cast(self._proposal_targets["labels"], tf.float32)],1)
    rois_target_image = tf.py_func(draw_bounding_boxes,
                      [self._gt_image, boxes, self._im_info, "rois_targets"],
                      tf.float32, name="rois_targets")
    return tf.summary.image('1_ROIS_TARGETS', rois_target_image), rois_target_image

**Comment by rnsandeep** [comment]
The library only visualizes the ground truth boxes. Use this file https://github.com/rnsandeep/ObjectDetection/blob/master/visualize_boxes_network.py
I had written functions to visualize anchor boxes, target boxes, prediction boxes.

**Comment by kemangjaka** [comment]
Thank you so much for sharing the code! 
I'm closing the issue.

**Comment by kemangjaka** [comment]
close
