### ISSUE TITLE
Wrong results in demo

### ISSUE THREAD

**Issue by azadef** [endernewton/tf-faster-rcnn#208]
I am trying to run the demo on a Tegra TX2 (aarch64), but the detection results are wrong. I ran the same code with the same models on a laptop and get correct results, tensorflow is also working fine in the same machine but with different projects.

Here are the system specifications:

Ubuntu 16.04
Cuda 8.0
cudnn 5.0
Tensorflow 1.2.1

I compiled the library with different gencode values, but it still doesn't work.
I get no error, except for a warning while compiling the lib folder, which says numpy_api is deprecated.

I also tried disabling nms and gpu_nms, but it didn't work.

**Comment by endernewton** [comment]
maybe first set gpu nms to false as a solution? i will test the the tensorflow nms and see if it works as fast.

**Comment by azadef** [comment]
I had set gpu nms to false, but it still doesn't work.
I don't think the problem is related to nms, I am getting high scores (over 0.9) for wrong classes, many wrong bounding boxes for each demo image.

**Comment by azadef** [comment]
The problem was in crop_pool_layer, I replaced it with roi_pool_layer from [this](https://github.com/smallcorgi/Faster-RCNN_TF) implementation and it works fine now.

**Comment by endernewton** [comment]
Wait there is an issue with the crop pooling layer?

**Comment by azadef** [comment]
Yes, only on Tegra tx2, on laptop it works fine.

**Comment by henryliang105** [comment]
I got same error detect result on tx2, how to replaced it with roi_pool_layer ??
