### ISSUE TITLE
vgg16.weights?

### ISSUE THREAD

**Issue by Data-drone** [endernewton/tf-faster-rcnn#22]
I am trying to test out the demo code using
`./experiments/scripts/test_vgg16.sh 0 pascal_voc`

I followed the tutorial and only have a vgg16.cpkt file rather than a .weights file?

**Comment by pavelboyko** [comment]
The file is downloaded by 
```
./data/scripts/fetch_imagenet_weights.sh
```
which is mentioned earlier in the tutorial. I had to use a backup server to make it work using the following line 7 of the script
```
URL=http://gs11655.sp.cs.cmu.edu/xinleic/tf-faster-rcnn/$FILE
```

I guess the codebase is in a transition from using caffe weights for vgg16 (see lib/nets/vgg16_depre.py) to native TF format for vgg16 and resnet101 (see lib/nets/vgg16.py). Hope the author will comment on this.

**Comment by Data-drone** [comment]
Sorted but I had to edit `create_architecture` in `vgg16_depre.py` to get the weights loaded:

On line 447:
`with open(self._caffe_weight_path, 'rb') as f:
      self._caffe_layers = pickle.load(f, encoding='latin-1')`
rather than
`with open(self._caffe_weight_path, 'r') as f:
      self._caffe_layers = pickle.load(f)`

in order to make it work with Python 3.
