### ISSUE TITLE
Is possible to use TIFF file as input?

### ISSUE THREAD

**Issue by John1231983** [endernewton/tf-faster-rcnn#222]
Hello, my input file is tiff file with type is uint16. Could we use this file as input for training? Thanks

**Comment by endernewton** [comment]
i think so, as long as you can convert it to rgb.

**Comment by John1231983** [comment]
@endernewton: Thanks for your reply. I choose the tiff because RGB only contains grayscale [0~255], while my original image is uint16 bit scale. If I store it as RGB format, I will lose the information. Hence, converting is not good option for my case

**Comment by endernewton** [comment]
@John1231983 who knows, try and see.
