### ISSUE TITLE
Error with "Build the Cython modules"

### ISSUE THREAD

**Issue by SAVeselovskiy** [endernewton/tf-faster-rcnn#227]
Got the error at 'make' cython modules step - `$ make`:

`g++ -pthread -shared -B /home/sergey/anaconda2/compiler_compat -L/home/sergey/anaconda2/lib -Wl,-rpath=/home/sergey/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/nms/nms_kernel.o build/temp.linux-x86_64-2.7/nms/gpu_nms.o -L/usr/local/cuda-8.0/lib64 -L/home/sergey/anaconda2/lib -R/usr/local/cuda-8.0/lib64 -lcudart -lpython2.7 -o /home/sergey/frcnn/tf-faster-rcnn/lib/nms/gpu_nms.so
`
`
g++: error: unrecognized command line option ‘-R’
`
`
error: command 'g++' failed with exit status 1
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
`

Whole output
`python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
building 'utils.cython_bbox' extension
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -B /home/sergey/anaconda2/compiler_compat -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sergey/.local/lib/python2.7/site-packages/numpy/core/include -I/home/sergey/anaconda2/include/python2.7 -c utils/bbox.c -o build/temp.linux-x86_64-2.7/utils/bbox.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -B /home/sergey/anaconda2/compiler_compat -L/home/sergey/anaconda2/lib -Wl,-rpath=/home/sergey/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/utils/bbox.o -L/home/sergey/anaconda2/lib -lpython2.7 -o /home/sergey/frcnn/tf-faster-rcnn/lib/utils/cython_bbox.so
skipping 'utils/nms.c' Cython extension (up-to-date)
building 'utils.cython_nms' extension
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -B /home/sergey/anaconda2/compiler_compat -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sergey/.local/lib/python2.7/site-packages/numpy/core/include -I/home/sergey/anaconda2/include/python2.7 -c utils/nms.c -o build/temp.linux-x86_64-2.7/utils/nms.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -B /home/sergey/anaconda2/compiler_compat -L/home/sergey/anaconda2/lib -Wl,-rpath=/home/sergey/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/utils/nms.o -L/home/sergey/anaconda2/lib -lpython2.7 -o /home/sergey/frcnn/tf-faster-rcnn/lib/utils/cython_nms.so
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
building 'nms.cpu_nms' extension
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -B /home/sergey/anaconda2/compiler_compat -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sergey/.local/lib/python2.7/site-packages/numpy/core/include -I/home/sergey/anaconda2/include/python2.7 -c nms/cpu_nms.c -o build/temp.linux-x86_64-2.7/nms/cpu_nms.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -B /home/sergey/anaconda2/compiler_compat -L/home/sergey/anaconda2/lib -Wl,-rpath=/home/sergey/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/nms/cpu_nms.o -L/home/sergey/anaconda2/lib -lpython2.7 -o /home/sergey/frcnn/tf-faster-rcnn/lib/nms/cpu_nms.so
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
building 'nms.gpu_nms' extension
{'gcc': ['-Wno-unused-function'], 'nvcc': ['-arch=sm_52', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"]}
/usr/local/cuda-8.0/bin/nvcc -I/home/sergey/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-8.0/include -I/home/sergey/anaconda2/include/python2.7 -c nms/nms_kernel.cu -o build/temp.linux-x86_64-2.7/nms/nms_kernel.o -arch=sm_52 --ptxas-options=-v -c --compiler-options '-fPIC'
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z10nms_kernelifPKfPy' for 'sm_52'
ptxas info    : Function properties for _Z10nms_kernelifPKfPy
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 22 registers, 1280 bytes smem, 344 bytes cmem[0], 12 bytes cmem[2]
{'gcc': ['-Wno-unused-function'], 'nvcc': ['-arch=sm_52', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"]}
gcc -pthread -B /home/sergey/anaconda2/compiler_compat -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sergey/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-8.0/include -I/home/sergey/anaconda2/include/python2.7 -c nms/gpu_nms.cpp -o build/temp.linux-x86_64-2.7/nms/gpu_nms.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/sergey/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /home/sergey/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/sergey/.local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from nms/gpu_nms.cpp:346:
/home/sergey/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
g++ -pthread -shared -B /home/sergey/anaconda2/compiler_compat -L/home/sergey/anaconda2/lib -Wl,-rpath=/home/sergey/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/nms/nms_kernel.o build/temp.linux-x86_64-2.7/nms/gpu_nms.o -L/usr/local/cuda-8.0/lib64 -L/home/sergey/anaconda2/lib -R/usr/local/cuda-8.0/lib64 -lcudart -lpython2.7 -o /home/sergey/frcnn/tf-faster-rcnn/lib/nms/gpu_nms.so
`
`
g++: error: unrecognized command line option ‘-R’
`
`
error: command 'g++' failed with exit status 1
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
`

Environment:
Tensorflow - 1.3.0
CUDA Toolkit - 8.0
cudnn - 6.0.21 
python - anaconda for python 2.7

What should i do to make it works?

**Comment by SAVeselovskiy** [comment]
Seems to work with default python... What may be wrong with anaconda?

**Comment by endernewton** [comment]
g++? i am not an expert in this but the output is complaining about the option -R

**Comment by SophieZhou** [comment]
How do you solved this problem? I have met the same problem. @endernewton

**Comment by SAVeselovskiy** [comment]
@SophieZhou in my case it worked with default python and didn't work with anaconda. I just removed anaconda and install all with virtualenv. Now everything is fine but i don't know the reason why it didn't work with anaconda

**Comment by endernewton** [comment]
thanks @SAVeselovskiy! closing.
