### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by guyan277** [endernewton/tf-faster-rcnn#228]
when i ran

GPU_ID=0
./experiments/scripts/test_faster_rcnn.sh $GPU_ID pascal_voc_0712 res101

and the process was complete, comes out this message

IOError: [Errno 2] No such file or directory: '/home/guyan/tf-faster-rcnn/data/VOCdevkit2007/results/VOC2007/Main/comp4_58c2f946-ac5a-4cbe-8325-cfbb0c94d3ba_det_test_aeroplane.txt'

is this 'results' folder generated after the training? Course there is no such folder in the downloaded test set of 2007.

If you have the folder, can you share it? The pre-trained model is already given, its pointless to train the data set again.
@endernewton

**Comment by guyan277** [comment]
solved by manually create the path...

**Comment by endernewton** [comment]
thanks!

-Xinlei
