### ISSUE TITLE
81-class object detector?

### ISSUE THREAD

**Issue by LiZimo** [endernewton/tf-faster-rcnn#229]
It seems there are some models trained on MS-COCO which has 80 object classes.  

Are the saved models trained to detect these classes, or are all saved models only trained for the 21 pascal-voc classes?  

If so, what is the best way to demo/test the 80-object detector network.  If not, is there an easy way to train for the 80 object version?  Any advice appreciated, thanks!

**Comment by LiZimo** [comment]
A code snippet of how to run the demo script with the 80 class version would suffice.  Thanks.

**Comment by LiZimo** [comment]
Think I figured it out.

**Comment by wyman-Y** [comment]
hello, I meet the same problem. Could you tell me how to solve? @LiZimo

**Comment by LiZimo** [comment]
Look in **lib/nets/resnet_v1.py** for full details.  

You can instantiate the 81 class detector as follows: 
-------------------------------------------------------------------------------------------------
net = resnetv1(num_layers=152)
net.create_architecture("TEST", 81,
						  tag='default', anchor_scales=[4,8,16,32])
saver = tf.train.Saver()
saver.restore(sess, tfmodel)
-------------------------------------------------------------------------------------------------

the model file **tfmodel** has to be downloaded from their google drive.  I think there are several model files that work.  The one I used is "res152_faster_rcnn_iter_1190000.ckpt".  [Download model files](https://drive.google.com/drive/folders/0B1_fAEgxdnvJSmF3YUlZcHFqWTQ). Once you open their drive, click on res152 for the relevant model files.  

The demo code walks you through how to use the 81 class detector - their api works the exact same as the default network.  

The classes are, in order: 
---------------------------------------------------------------------------------------------------------------------------
CLASSES = ('__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush')
----------------------------------------------------------------------------------------------------------------------------

Hope this helps.

**Comment by wyman-Y** [comment]
That's OK ! Thank you ! @LiZimo
