### ISSUE TITLE
Sizes do not match - Help needed to simply load a pretrained model!

### ISSUE THREAD

**Issue by yoniker** [endernewton/tf-faster-rcnn#234]
Hi!

So I've followed the intructions, and when it tries to load the net there's an error- sizes do not match.
I will put the detailed error at the bottom.
Maybe that has something to do with another thing:
When it comes to resnet101,in Google drive itself there's the file
res101_faster_rcnn_iter_1190000.pth

While the original demo.py code was looking for something like res101_faster_rcnn_iter_110000.pth

Honestly, all I want is to run a pretrained (on COCO) faster-RCNN model on some pictures ;)
Help will be super appreciated!

Thanks in advance,
Yoni.

While copying the parameter named bbox_pred_net.bias, whose dimensions in the model are torch.Size([84]) and whose dimensions in the checkpoint are torch.Size([324]), ...
Traceback (most recent call last):
  File "demo.py", line 140, in <module>
    net.load_state_dict(torch.load(saved_model))
  File "/home/yoni/Projects/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 497, in load_state_dict
    nn.Module.load_state_dict(self, {k: state_dict[k] for k in list(self.state_dict())})
  File "/home/yoni/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 360, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:95

**Comment by endernewton** [comment]
i don't have a pytorch thingy, closing. however, you may have built a voc graph but want to load a coco one (or the other way around).
