### ISSUE TITLE
How to run demo on GPU ID 1 instead of GPU ID 0

### ISSUE THREAD

**Issue by satya2550** [endernewton/tf-faster-rcnn#239]
My machine is having 2 GPUs  of GPU model : GTX 1080 (Ti).
Each is having 12 GB GPU Memory.
Can you help in running demo or prediction on both GPUs

**Comment by engineer1109** [comment]
If you are ubuntu,
you can run this sh,

GPU_ID=1
CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py

**Comment by endernewton** [comment]
thanks @engineer1109! closing.
