### ISSUE TITLE
test_faster_rcnn.sh result file not found

### ISSUE THREAD

**Issue by TinusChen** [endernewton/tf-faster-rcnn#246]
Run:
./experiments/scripts/test_faster_rcnn.sh  0 pascal_voc res101

Error log:
im_detect: 1198/1200 0.150s 0.016s
im_detect: 1199/1200 0.150s 0.016s
Evaluating detections
Writing crane VOC results file
Traceback (most recent call last):
  File "./tools/test_net.py", line 120, in <module>
    test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
  File "/path/to/my/tf-faster-rcnn-master/tools/../lib/model/test.py", line 192, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/path/to/my/tf-faster-rcnn-master/tools/../lib/datasets/pascal_voc.py", line 277, in evaluate_detections
    self._write_voc_results_file(all_boxes)
  File "/path/to/my/tf-faster-rcnn-master/tools/../lib/datasets/pascal_voc.py", line 204, in _write_voc_results_file
    with open(filename, 'wt') as f:
IOError: [Errno 2] No such file or directory: '/path/to/my/tf-faster-rcnn-master/data/VOCdevkit2007/results/VOC2007/Main/comp4_04d40519-2eb7-49c9-aff7-db661169d037_xxxx.txt'
Command exited with non-zero status 1
245.75user 46.13system 5:07.37elapsed 94%CPU (0avgtext+0avgdata 2098228maxresident)k
18152inputs+7296outputs (49major+2198593minor)pagefaults 0swaps

**Comment by TinusChen** [comment]
Try OK:
mkdir -p /path/to/my/tf-faster-rcnn-master/data/VOCdevkit2007/results/VOC2007/Main/

**Comment by endernewton** [comment]
thanks! closing.

**Comment by zqdeepbluesky** [comment]
hi I did everything like you,and I get AP on my dataset,but the result didn't write back to / data / VOCdevkit2007 / results / VOC2007 / Main /comp4_04d40519-2eb7-49c9-aff7-db661169d037_xxxx.txt, can you tell me how to get result.txt?thanks a lot.

**Comment by Emma-uestc** [comment]
> hi I did everything like you,and I get AP on my dataset,but the result didn't write back to / data / VOCdevkit2007 / results / VOC2007 / Main /comp4_04d40519-2eb7-49c9-aff7-db661169d037_xxxx.txt, can you tell me how to get result.txt?thanks a lot.

Do you solve this problem? it does exist this kind of error after each training,I did everything like you,created the directory like ./tf-faster-rcnn/data/VOCdevkit2007/results/VOC2007/... or ./tf-faster-rcnn/data/VOCdevkit/VCO2007/...after each training error

**Comment by duydangg** [comment]
> Try like this (OK):
> mkdir -p /path/to/my/tf-faster-rcnn-master/data/VOCdevkit2007/results/VOC2007/Main/

hey i just made the folder but it still doensnt work, can you fix it
