### ISSUE TITLE
mAP calculation very high for my dataset. Is it wrong?

### ISSUE THREAD

**Issue by John1231983** [endernewton/tf-faster-rcnn#249]
Thanks for the great project. It helps me so much. I am using it for my dataset. I achieved very good result. Right now, I am performing the evaluation of detection using mAP. I have 5 classes and the prediction (red) and ground-truth (blue) are very close for each class as the figure. 

![untitled](https://user-images.githubusercontent.com/24875971/33157177-7d6de0dc-d043-11e7-8635-76741216dad1.png)

When I use `./experiments/scripts/test_faster_rcnn.sh 0 dataset res101`, I got 100% of mAP. It looks very high although some classes (class 4 and 5) are not totally overlapping. From the above figure, do you think mAP calculation is correct? Thanks 
This is output of testing

```
im_detect: 1/1 0.938s 0.001s
Evaluating detections
VOC07 metric? No
AP for class1 = 1.0000
AP for class2 = 1.0000
AP for class3 = 1.0000
AP for class4 = 1.0000
AP for class5 = 1.0000
Mean AP = 1.0000
~~~~~~~~
Results:
1.000
1.000
1.000
1.000
1.000
1.000
~~~~~~~~

```

**Comment by endernewton** [comment]
it is calculated based on an iou of .5, so should be 1.000.

**Comment by John1231983** [comment]
Thanks for your reply. It is correct that it depends on IoU thresh of 0.5. However, when I test another image, it still shows 100% of class 5, even it is a fail detection. The output image is obtained by running `demo.py`, while the below report is from  `experiments/scripts/test_faster_rcnn.sh`

![untitled](https://user-images.githubusercontent.com/24875971/33363201-b3d72fe6-d522-11e7-9703-3d5ce3dd65b5.png)

Overlap of class  1 is : 0.812461394181
Recall, Prec, AP of class  1 are : [ 1.] [ 1.] 1.0
AP for 1dp3 = 1.0000
Overlap of class  2 is : 0.919351656138
Recall, Prec, AP of class  2 are : [ 1.] [ 1.] 1.0
AP for 2mp3 = 1.0000
Overlap of class  3 is : 0.9089039081
Recall, Prec, AP of class  3 are : [ 1.] [ 1.] 1.0
AP for 3pp3 = 1.0000
Overlap of class  4 is : 0.826044255536
Recall, Prec, AP of class  4 are : [ 1.] [ 1.] 1.0
AP for 4radius = 1.0000
Overlap of class  5 is : 0.6883700828
Recall, Prec, AP of class  5 are : [ 1.] [ 1.] 1.0
AP for 5ulna = 1.0000
Mean AP = 1.0000
~~~~~~~~
Results:
1.000
1.000
1.000
1.000
1.000
1.000
~~~~~~~~

**Comment by John1231983** [comment]
@endernewton : could you please explain above case for me? Thanks

**Comment by John1231983** [comment]
@endernewton: could you look at my problem?. It shows that it did not solved. Thsbks

**Comment by endernewton** [comment]
here what do you mean by the line: Overlap of class 5 is : 0.6883700828?
what did you do exactly?

-Xinlei

**Comment by John1231983** [comment]
I did not change anything in measurement code just put the print lines. Then I  ran the code to show the prediction likes the figure and saw that when the class 5 is missing but it still have value of overlapping like 0.688.

**Comment by endernewton** [comment]
print what ? can you copy paste it? also if you are showing on the figure
like the demo does, the demo actually has another threshold on the
confidence -- and such a threshold is not used in the evaluation code for
map.

-Xinlei

**Comment by John1231983** [comment]
Sorry for reply late!
The above log is in the voc_val.py function. I did not change the setting (same as ovthresh=0.5) and add the print line to line [194](https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/datasets/voc_eval.py#L194) as
```
print ('Overlap of class ',classname, 'is :',ovmax)
```
And line [213](https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/datasets/voc_eval.py#L213)
```
print('Recall, Prec, AP of class ', classname, 'are :',  rec, prec, ap)
```

In demo, I changed the `CONF_THRESH = 0.8` to `0.95`, and unchanged  `NMS_THRESH = 0.3,  ANCHORS="[8,16,32]"   RATIOS="[0.5,1,2]",  cfg.TEST.HAS_RPN = True`

The different with model/test.py is that I did not subtract image image likes `  im_orig -= cfg.PIXEL_MEANS`. I did not find any setting for `CONF_THRESH` in testing code. You means it is thresh=0 as the function `def test_net(sess, net, imdb, weights_filename, max_per_image=100, thresh=0.):`
