### ISSUE TITLE
Why i using the res101 to train the faster-rcnn  on my own dataset so slow? 

### ISSUE THREAD

**Issue by powermano** [endernewton/tf-faster-rcnn#251]
I  have tested the voc2007 using the Resnet101  pre-trained on 07+12 set, for a single image, i need nearly 10S for detection, is this reasonable？ (I finally get the 78 map)
And when i use res101 to train my own data, (i only use 150 images as the training set)  speed is 38S/iter. Is this reasonable?

**Comment by endernewton** [comment]
are u using cpu version of tf?

**Comment by powermano** [comment]
i install the tensorflow(version1.2) for gpu. And when i train my network,i use the command 'nvidia-smi' ,and i find the GPU actually works.  I do not change any other codes except the classes in the pascal_voc.py and iters in the train_faster_rcnn.sh and also test_faster_rcnn for my own dataset.
