### ISSUE TITLE
A question about the bbox_transform_inv function

### ISSUE THREAD

**Issue by lonlonago** [endernewton/tf-faster-rcnn#253]
In the test.py file's im_dect() function,  test.py line 95 ,there is : 

  boxes = rois[:, 1:5] / im_scales[0]
  scores = np.reshape(scores, [scores.shape[0], -1])
  bbox_pred = np.reshape(bbox_pred, [bbox_pred.shape[0], -1])
  if cfg.TEST.BBOX_REG:
    # Apply bounding-box regression deltas
    box_deltas = bbox_pred
    pred_boxes = bbox_transform_inv(boxes, box_deltas)

why the rois should divide im_scales[0] ？this make the rois based on original image size？so, the 
 bbox_transform_inv is also based on original image size, but in 
proposal_target_layer, the box_target is  calculated  based on resized image, how to explain this contradiction?

**Comment by endernewton** [comment]
the network needs to be trained to predict the resized image, otherwise the prediction does not make sense -- the original image size can be arbitrary and there is no way to predict it.

**Comment by lonlonago** [comment]
then why first do this?  boxes = rois[:, 1:5] / im_scales[0]  and then pred_boxes = bbox_transform_inv(boxes, box_deltas), in my mind it should be pred_boxes = bbox_transform_inv(rois, box_deltas) , then pred_boxes = pred_boxes / im_scales[0].
