### ISSUE TITLE
How to compute the PIXEL_MEANS in my custom dataset?

### ISSUE THREAD

**Issue by John1231983** [endernewton/tf-faster-rcnn#266]
Hello, I found that the PIXEL_MEANS was used in the file config.py. I want to use the project in my custom dataset that includes gray images with .png type. Could you suggest to  me how to calculate the PIXEL_MEANS? Thanks

**Comment by endernewton** [comment]
you can, yet it may not be necessary, currently the same pixel mean is used across different networks and they seem to work just fine. so unless you are applying it to a very different domain (like medical imaging), it may not be necessary.
