### ISSUE TITLE
why 'trainable = false' in conv1,conv2，how to initialize when inference？

### ISSUE THREAD

**Issue by liangzz1991** [endernewton/tf-faster-rcnn#275]
net = slim.repeat(self._image, 2, slim.conv2d, 64, [3, 3],
                          trainable=False, scope='conv1')
net = slim.max_pool2d(net, [2, 2], padding='SAME', scope='pool1')
net = slim.repeat(net, 2, slim.conv2d, 128, [3, 3],
                        trainable=False, scope='conv2')

**Comment by endernewton** [comment]
it is initialized with the image-net pretrained models.
