### ISSUE TITLE
Why the criterion for positive samples is different between RPN and the following per-region classifier 

### ISSUE THREAD

**Issue by yaoqi-zd** [endernewton/tf-faster-rcnn#277]
excellent repo! I just wonder why the criterion for positive samples is different in RPN and per-region classifier:
In RPN, those anchors whose IoU with gt higher than 0.7 are treated as positive, while lower than 0.3 are treated as negatives
In the following per-region classifier, proposals whose IoU with gt higher than 0.5 are treated as positive and the others are negatives.
I just wonder why the criterion is different between RPN and per-region classifier, since they are both classification problem?

**Comment by endernewton** [comment]
thanks! it is just parameters copied from the original faster rcnn. i think they must have done some search to find this pair working well on the validation set.
