### ISSUE TITLE
Training on GPU is much slower than py-faster-rcnn

### ISSUE THREAD

**Issue by PamixSun** [endernewton/tf-faster-rcnn#281]
Using both tf-faster-rcnn and py-faster-rcnn to train a VGG16 Network on GPU, I found that the former one   is much slower than the latter one. 

To make sure that both algorithm are using GPU, I type 'nvidia-smi' in console and get the following messages:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp            Off  | 00000000:05:00.0 Off |                  N/A |
| 36%   63C    P2   262W / 250W |   3718MiB / 12188MiB |     31%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:06:00.0 Off |                  N/A |
| 33%   55C    P2    63W / 250W |    324MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN Xp            Off  | 00000000:09:00.0 Off |                  N/A |
| 23%   32C    P8     9W / 250W |     10MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     31589      C   python3                                     3708MiB |
|    1      4508      C   python3                                      314MiB |
+-----------------------------------------------------------------------------+

Note that tf-faster-rcnn is running on GPU-1 while py-faster-rcnn is on GPU-0.

It is strange that the GPU-Util for GPU-1 (on which tf-faster-rcnn runs) is 0%.

I would like to know if the code works properly.

Thank you.

**Comment by endernewton** [comment]
your gpu is not used.. please check if you have installed a cpu tf?

-Xinlei

**Comment by PamixSun** [comment]
@endernewton Yes I have installed both tensorflow and tensorflow-gpu. 

So dose it mean I have to uninstall tensorflow?

Thank you.

**Comment by PamixSun** [comment]
@endernewton Fix it by re-install tensorflow-gpu
