### ISSUE TITLE
im_orig -= cfg.PIXEL_MEANS

### ISSUE THREAD

**Issue by engineer1109** [endernewton/tf-faster-rcnn#289]
im_orig -= cfg.PIXEL_MEANS
What does cfg.PIXEL_MEANS mean? And what is its function?
Why is it a constant?
The mean of the picture RGB is dynamic

**Comment by endernewton** [comment]
the imagenet trained models have the pixel mean extracted. so it is just to align the data. it was mentioned in the original faster rcnn that the const mean and the location sensitive mean do not matter too much in performance, so i followed suit
