### ISSUE TITLE
About OHEM

### ISSUE THREAD

**Issue by philokey** [endernewton/tf-faster-rcnn#29]
Do you plan to add OHEM?

**Comment by endernewton** [comment]
Maybe sometime later (not before June). If you are interested, you can
start implementing it.

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA

**Comment by philokey** [comment]
Ok, I will try it.

Xinlei Chen <notifications@github.com>于2017年3月30日周四 下午11:18写道：

**Comment by endernewton** [comment]
Thanks! Looking forward! :+1:
