### ISSUE TITLE
how to export trained detection model for tensorflow serving

### ISSUE THREAD

**Issue by zbxzc35** [endernewton/tf-faster-rcnn#291]

**Comment by endernewton** [comment]
i don't think it could at tf 1.2. Not sure if they can do that in newer versions..

**Comment by endernewton** [comment]
Please see this pull request: https://github.com/endernewton/tf-faster-rcnn/pull/307 for help. Thanks!

**Comment by zbxzc35** [comment]
Awesome!thanks for your notification!!!
