### ISSUE TITLE
annotations with 'iscrowd=1'

### ISSUE THREAD

**Issue by xiaoyuliu** [endernewton/tf-faster-rcnn#297]
Hi,

Thanks for the effort. I'm recently generating a subset from MSCOCO, and I noticed you have some operations on bboxes where `iscrowd=1`.
```python
    for ix, obj in enumerate(objs):
      cls = coco_cat_id_to_class_ind[obj['category_id']]
      boxes[ix, :] = obj['clean_bbox']
      gt_classes[ix] = cls
      seg_areas[ix] = obj['area']
      if obj['iscrowd']:
        # Set overlap to -1 for all classes for crowd objects
        # so they will be excluded during training
        overlaps[ix, :] = -1.0
      else:
        overlaps[ix, cls] = 1.0
```

 Why not simply remove all bboxes['iscrowd'] = 1? Because they seem useless or even misleading in training.

**Comment by endernewton** [comment]
this is to have a fair comparison with previous numbers, i also found that issue, but find that whether including the crowd instances or not the performance is similar (at least with the way current eval is done), so followed previous implementation of py-faster-rcnn.
