### ISSUE TITLE
ImportError:No module named pycocotools.coco

### ISSUE THREAD

**Issue by jsjs0827** [endernewton/tf-faster-rcnn#3]
When I am in your STEP test and train,the terminal show me the error.
from pycocotools.coco import COCO
I cannot find the folder or document named pycocotools,can you give me some suggestions?Thank you so much for your help,hope to hear from you.

**Comment by endernewton** [comment]
You need to create a link in data folder, following what you do when you set up pay-fast-rcnn.

**Comment by abhiML** [comment]
For training with pascal_voc why do I get this issue?
