### ISSUE TITLE
Reproducing problem

### ISSUE THREAD

**Issue by bareblackfoot** [endernewton/tf-faster-rcnn#300]
I run the code for training faster rcnn with vgg16 on pascal voc 2007 dataset. 
The result of it is different from the announced one. 
I am not sure, but I think it has reproducing problem. As I found,
1) The tf.set_random_seed should be called before the session created.
2) All random operations in tensorflow need "seed= cfg.RNG_SEED" option.

(For @endernewton ) Have you ever trained the network on other computers for checking random seed?

**Comment by endernewton** [comment]
What is the performance difference? And which tf version are you using?

Sent from my iPhone

On Feb 14, 2018, at 8:10 PM, Nuri <notifications@github.com<mailto:notifications@github.com>> wrote:


I run the code for training faster rcnn with vgg16 on pascal voc 2007 dataset.
The result of it is different from the announced one.
I am not sure, but I think it has reproducing problem. As I found,

  1.  The tf.set_random_seed should be called before the session created.
  2.  All random operations in tensorflow need "seed= cfg.RNG_SEED" option.

(For endernewton) Have you ever trained the network on other computers for checking random seed?

**Comment by bareblackfoot** [comment]
The version is 1.4 and actually, my result has better performance than the reported one, about 71.4 mAP.(reported : 70.8 mAP)

**Comment by endernewton** [comment]
Haha then there is nothing wrong with that. :P

**Comment by bareblackfoot** [comment]
You closed this issue, but I found that when your code calls validation data, it set a random seed using the current time and didn't set the given random seed again. haha.

**Comment by yaoqi-zd** [comment]
@endernewton emm... I'm a littile confused, don't you think 0.6 mAP gap (70.8 vs 71.4) is not ignorable in object detection field? 
should we fix the random seed when sample anchors (in anchor_target_layer) and proposal (in proposal_target_layer) to make a more stable results?

**Comment by endernewton** [comment]
The thing is, it is hard. I already tried to fix the random seeds for numpy. However especially the use of cudnn will cause randomness in training anyway.

0.6 is not big for pascal. within 1 is normal in my experience.

Regards,
Xinlei

________________________________________
