### ISSUE TITLE
Implementation difference compared to the one in the Tensorflow `models` repo?

### ISSUE THREAD

**Issue by ywpkwon** [endernewton/tf-faster-rcnn#303]
Thanks for sharing this great work!

I found that there is also another Faster RCNN implementation in the Tensorflow `models` repository (https://github.com/tensorflow/models/tree/master/research/object_detection). Could you provide some insight about how this implementation is different than the one in the `models` repo?

**Comment by endernewton** [comment]
i haven't checked their code carefully. their code is more modularized and engineering i would say, and supports multiple gpu training.
