### ISSUE TITLE
Low mAP Score on my custom data set.

### ISSUE THREAD

**Issue by satya2550** [endernewton/tf-faster-rcnn#305]
@endernewton , Hi we are working on custom images in which we have done annotation like object inside object kind of thing, for ex : Bus picture has car and other objects on it.
Due to this our mAP score is reducing to 30% , earlier it was 75%. How to improve the score.
Or Do i need to change mAP calculation logic

**Comment by endernewton** [comment]
I am not sure having objects inside other objects can cause such a reduction, especially for different classes. because deduplication (nms) is done separately for each class.
