### ISSUE TITLE
mobilenet  fix RGB to BGR, and match the scale by (255.0 / 2.0) why？

### ISSUE THREAD

**Issue by L-CY** [endernewton/tf-faster-rcnn#310]
mobilenet_v1.py line 271, 277
# fix RGB to BGR, and match the scale by (255.0 / 2.0)
sess.run(tf.assign(self._variables_to_fix[self._scope + "/Conv2d_0/weights:0"], 
               tf.reverse(Conv2d_0_rgb / (255.0 / 2.0), [2])))

Could you tell me what 255.0/2.0 means. I noticed that in resnet, vgg16, such implementation is not needed. I read the paper but could not find any explanation.
Thank you.

**Comment by endernewton** [comment]
oh it is just that mobilenet has a different way of preprocessing the data.
