### ISSUE TITLE
distributed version

### ISSUE THREAD

**Issue by fanlu** [endernewton/tf-faster-rcnn#32]
Is there a distributed version?

**Comment by endernewton** [comment]
Not yet. Right now it is reading and feeding the data following faster rcnn (I also intended to fix random seeds but failed). A good way to start a distributed version is to first dump the data into tfrecords. However I am busy and will find time to do that later. You can try if you are interested (a separate trainval.py that reads tfrecords).

**Comment by bhack** [comment]
@fanlu You can find mscoco tfrecord in https://github.com/CharlesShang/FastMaskRCNN
