### ISSUE TITLE
Can I change the anchor size?

### ISSUE THREAD

**Issue by aldarabs** [endernewton/tf-faster-rcnn#33]
How can I change the anchor size of the RPN to 16^2, 40^2, 100^2 instead of 128^2, 256^2, 512^2? Also, How can I attach the feature maps from conv4_3 to anchor boxes instead conv5_3?

**Comment by endernewton** [comment]
You can now. ANCHOR_SCALES is the option. Do not have extra spaces inputing the array.

**Comment by hadi-ghnd** [comment]
@aldarabs have you figured out how to attach feature maps from conv4_3 instead of conv5_3?
 thanks
