### ISSUE TITLE
Why does (RPN's result reshape to [-1,4]) work?

### ISSUE THREAD

**Issue by guotong1988** [endernewton/tf-faster-rcnn#34]
https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/layer_utils/proposal_layer.py#L30

As `rpn_bbox_pred` is just the result of `conv`, so this confused me.

**Comment by endernewton** [comment]
Check Ross's original version. Thanks.

**Comment by guotong1988** [comment]
I'm not querying correctness..

**Comment by guotong1988** [comment]
@endernewton Could you please explain the reason?
