### ISSUE TITLE
Can I use python 3.5 ?

### ISSUE THREAD

**Issue by motoleisure404** [endernewton/tf-faster-rcnn#343]
Can I use python 3.5 ?

**Comment by DAA233** [comment]
I think you can, I have run it with Python 3.6.5.

**Comment by surajitsaikia27** [comment]
To use python 3.5 you need to change the code to make it python3.5 compatible. Recently, I have converted it into python3.x compatible.
https://github.com/surajitsaikia27/PY3-Faster-RCNN-TF
