### ISSUE TITLE
Res101 demo 

### ISSUE THREAD

**Issue by bhack** [endernewton/tf-faster-rcnn#35]
After the last resnet accurancy improvment results do you plan to adapt the demo for res101 model?

**Comment by bhack** [comment]
I think that test_net.py it is aligned more then demo.py that still use the old caffe weights.

**Comment by endernewton** [comment]
Writing a demo is not the hardest thing to do... maybe you can submit a better one than the current?

**Comment by bhack** [comment]
I have a local hack.. I will try to open a PR next week

**Comment by bhack** [comment]
Is here https://github.com/endernewton/tf-faster-rcnn/pull/37. I've not added mscoco cause I still don't know its status.

**Comment by endernewton** [comment]
Great! Thanks! I will incorporate it and update the readme later today.

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA

**Comment by bhack** [comment]
One question.. why you have used custom nms code and not the tf ones?

**Comment by bhack** [comment]
Ok probably you could contribute nms gpu upstream for https://github.com/tensorflow/tensorflow/issues/7511 😉

**Comment by endernewton** [comment]
Haha thanks!
