### ISSUE TITLE
while running demo.py: tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested in session .py 

### ISSUE THREAD

**Issue by Medj9** [endernewton/tf-faster-rcnn#364]
When i run demo.py file i got the following error
File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): Read less bytes than requested
	 [[Node: save/RestoreV2_529 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_529/tensor_names, save/RestoreV2_529/shape_and_slices)]]

**Comment by navinthenapster** [comment]
may I know how you solved it

**Comment by zhangbo2008** [comment]
i comeinto the  same problem .how to solve?

**Comment by zhangbo2008** [comment]
today, i redownload the model of ResNet(340mb) and solve the problem
