### ISSUE TITLE
no CUDA-capable device is detected

### ISSUE THREAD

**Issue by kevinkit** [endernewton/tf-faster-rcnn#38]
When executing the command

`CUDA_VISIBLE_DEVICES=$0 ./tools/demo.py `

I get greeted with "no CUDA-capable device is detected" - however I have a TITAN X on Ubuntu 16.04 with CUDA installed, running nvidia-smi gives me the Device-ID of 0, so what could be the problem here?

**Comment by bhack** [comment]
CUDA_VISIBLE_DEVICES=0
