### ISSUE TITLE
Train with fewer classes?

### ISSUE THREAD

**Issue by shuang1330** [endernewton/tf-faster-rcnn#39]
Hi! I tried to train it with fewer classes, let's say 18 classes, without 'sofa', 'train', and 'tvmonitor'. This is what I changed:
1) pascal_voc.py: I deleted some classes:
    self._classes = ('__background__',  # always index 0
                     'aeroplane', 'bicycle', 'bird', 'boat',
                     'bottle', 'bus', 'car', 'cat', 'chair',
                     'cow', 'diningtable', 'dog', 'horse',
                     'motorbike', 'person', 'pottedplant',
                     'sheep')#, 'sofa', 'tvmonitor')#, 'train')
2) proposal_target_layer.py: I added:
  for ind in inds:
    cls = clss[ind]
    if cls >= num_classes:
        cls = 0
        
    start = int(4 * cls)
    end = start + 4
in def _get_bbox_regression_labels(bbox_target_data, num_classes) function

At some point, the model gives all cross_entropy to be [nan,nan,nan....nan], and the cls_scores are: [nan,nan,nan,..,nan], fc7 layers gives results of [0,0,0,0,.....]... 
I wonder anyone encountered similar problems? Or anyone has ideas about it..?

**Comment by endernewton** [comment]
i believe you need to change the anchor target gt as well.

**Comment by shuang1330** [comment]
Thank you for your reply. Could you point out more specifically on where to change the anchor target? I found it really difficult to follow the code and find where to change the parameters... 
Moreover, I wonder how you read the xml files for loading rois? The function in pascal_voc.py on loading annotations seems not to called during traing/testing procedures. Thank you in advance!

**Comment by endernewton** [comment]
seems like https://github.com/endernewton/tf-faster-rcnn/issues/56 already has made it work? So I think it is good to check it out with wang-tf. closing now.
