### ISSUE TITLE
bugs about using nms of tf version

### ISSUE THREAD

**Issue by kl456123** [endernewton/tf-faster-rcnn#400]
bbox format should be [ymin,xmin,ymax,xmax] in proposals_layer_tf file when using tf.image.non_max_suppression

**Comment by kl456123** [comment]
the same.....

**Comment by sun-su** [comment]
> the same.....

Hi kl456123,
Did you mean [xmin, ymin, xmax, ymax] and [ymin, xmin, ymax, xmax] generate same result?
