### ISSUE TITLE
ResNet101:Train on VOC 2007 trainval and test on VOC 2007 test, only 74.97？

### ISSUE THREAD

**Issue by 1451595897** [endernewton/tf-faster-rcnn#403]
I  train on VOC2007 according to your step and test on VOC2007,but the MAP is only  74.97,which is lower than yours(75.5).What is this problem and how can I deal with it?
![2018-11-30 21-01-11](https://user-images.githubusercontent.com/39090271/49291713-35f98300-f4e6-11e8-9763-9a69acd1b842.png)

**Comment by zqdeepbluesky** [comment]
@1451595897 hi ， I meet the same error ,how do you solve it ?
