### ISSUE TITLE
No sumarry files present at this path tensorboard --logdir=tensorboard/vgg16/voc_2007_trainval/ --port=7001 &

### ISSUE THREAD

**Issue by Medj9** [endernewton/tf-faster-rcnn#410]
Hi I had train the model according to the instructions but the summary file is not generated how can i visualize the graph
![screenshot from 2018-12-17 12-36-30](https://user-images.githubusercontent.com/40450303/50071663-95e76d80-01f8-11e9-8e5d-3aadbc1a8b1f.png)

**Comment by ZhuoyaYang** [comment]
Hello!Did you solved the problem?I don't find tensorboard file too.Do you kown the files generated when train or test?

**Comment by lululalamm** [comment]
I have the same problem. 
Please share your solution.

**Comment by shida666** [comment]
> Hello!Did you solved the problem?I don't find tensorboard file too.Do you kown the files generated when train or test


> Hello!Did you solved the problem?I don't find tensorboard file too.Do you kown the files generated when train or test?

你好 这个torchvision 的问题您解决了吗 我也是没有任何数据显示
