### ISSUE TITLE
Lower AP on voc2007.

### ISSUE THREAD

**Issue by Fansiee** [endernewton/tf-faster-rcnn#42]
I train the model on voc2007, but the test accuracy is only 0.693 compared with your result 71.2.
And when use the resnet101, my result is 0.7394 compared with your result 0.75.
Is it the random error?
Thanks!

**Comment by endernewton** [comment]
hmm maybe there is some small bug introduced in the recent updates. can you try:
- testing the provided model if you can get the same number? making sure your testing is ok
- train again and see the variance on your side?

i have got 69.9/74.2 before with nms testing.

**Comment by endernewton** [comment]
FYI, i tried training on COCO and with 350k/490k vgg16 training it does get lower than expected numbers (25.9 with nms testing), there might be some hidden bug introduced recently (it can be in TF, not just this code base) that lowered the performance or increased the variance. i am busy but will look into this in some time if there is a serious issue in reproducing the numbers (like in May/June).

**Comment by endernewton** [comment]
Just verified. Please use vgg16.sh for training as a temporary solution for now. I retrained it and it gets 26.4 AP with nms testing. This also means there is some subtle difference between the new version of vgg16 code and the old one. Debuggers are welcome.

**Comment by endernewton** [comment]
Bug (probably) fixed: the new code uses slim models, which assume RGB images instead BGR ones. Retraining models now. Thanks for the patience.

**Comment by rmekdma** [comment]
@endernewton 
Demo is still BGR image (and result is good)
https://github.com/endernewton/tf-faster-rcnn/blob/master/tools/demo.py#L80
Is this supposed to be modified?

**Comment by endernewton** [comment]
@rmekdma no it need not be, the weight is modified so it works fine with all opencv load.
