### ISSUE TITLE
bug @ demo.py

### ISSUE THREAD

**Issue by dimtziwnas** [endernewton/tf-faster-rcnn#45]
~/DL/tf-faster-rcnn$ CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py

    Traceback (most recent call last):
      File "./tools/demo.py", line 118, in <module>
        dataset = dataset
    NameError: name 'dataset' is not defined

**Comment by endernewton** [comment]
Thanks! I fixed the code but didn't test it. Does it work now?
