### ISSUE TITLE
vgg weights file

### ISSUE THREAD

**Issue by auroua** [endernewton/tf-faster-rcnn#46]
Does the training process and testing process using different vgg weights file?
From the source code, the training process needs to load a vgg16.ckpt file, but the demo.py needs a vgg16 weights file from caffe model.
Why not using ckpt weights model directly in demo.py?

**Comment by bhack** [comment]
Have u seen the master version?

**Comment by endernewton** [comment]
It is because the code has two versions, one with caffe weights loaded from a weights file (old one), and the one that uses weights loaded from a slim ckpt. Right now for demo.py you don't need vgg16 weights, but for demo_depre.py you need.

**Comment by auroua** [comment]
Thanks.
I followed the new code. It seems the new code still using caffe weights to initialize vgg16 net at first, and then using tfmodel to re-initialize the weights.
```
from nets.vgg16_depre import vgg16
```
Why not import vgg16 but import vgg16_depre.

**Comment by endernewton** [comment]
@bhack I guess I will fix it now. :) Thanks for pointing this out.

**Comment by auroua** [comment]
I guess in demo.py the following code have a bug
```
tfmodel = os.path.join('../output',demonet,DATASETS[dataset][0], 'default',
                              NETS[demonet][0])
```
the output path is  ../output/vgg16/v/default/v.meta, maybe ../output/vgg16/voc/vgg16.meta is more sensible.

**Comment by endernewton** [comment]
Hmm, seems this code is a bit troublesome. Could you fully test and modify
it and submit a PR? Right now the models I released should be compatible
with this code (except the old vgg16 voc07 model and vgg16 coco model). It
would be great to show demos for the voc07+12 models on both vgg16 and
resnet101.

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA

**Comment by auroua** [comment]
@endernewton 
ok, I will try.
