### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by JosephKJ** [endernewton/tf-faster-rcnn#47]
Please correct 'python-opencv' dependency to 'opencv-python' in the [Prerequisite](https://github.com/endernewton/tf-faster-rcnn#prerequisites) section. 

Reason:

While doing 
`pip install python-opencv` : 
`No matching distribution found for python-opencv`

and
`pip install opencv-python` : 
`Installing collected packages: numpy, opencv-python`
`Successfully installed numpy-1.12.1 opencv-python-3.2.0.7`

**Comment by bhack** [comment]
Can you do a quick PR?

**Comment by JosephKJ** [comment]
@bhack : Done!

I have another PR too. Kindly review.
