### ISSUE TITLE
How to train with FPN network?

### ISSUE THREAD

**Issue by baiyancheng20** [endernewton/tf-faster-rcnn#49]
@endernewton Hi, I want to know how to train the FPN network with your code? Thank you.

**Comment by bhack** [comment]
There is some FPN code in https://github.com/CharlesShang/FastMaskRCNN but still not here.

**Comment by endernewton** [comment]
i don't have code to train fpn here. you can use the link mentioned above if you want. I think fpn will improve performance so maybe will add it later.

**Comment by baiyancheng20** [comment]
@endernewton  In the readme file, 
> Train on COCO 2014 trainval35k and test on minival with approximate FPN baseline setup (900k/1290k), 35.8.

I thought you had implemented it.

**Comment by endernewton** [comment]
Nope. this is the baseline setting used in FPN. I should probably update my
readme.

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA
