### ISSUE TITLE
error when i run the demo when calling ./tools/demo_depre.py 

### ISSUE THREAD

**Issue by haysaka** [endernewton/tf-faster-rcnn#53]
Hi, i have followed the installation guide to install the faster rcnn on ubuntu16.04, i use GTX1080 and i don't change the arch from sm_52 to sm_61, and  line 49 of setu.py  i replace "pjoin(home, 'lib64')}" by pjoin(home, 'lib')},;  therefore this no error when i run make command. But, because i install tensorflow with python3,so i am not sure whether other changes should be done.
so the make is done. However, when i run step 3 in Test with (old) pre-trained models (Demo Included):
GPU_ID=1
CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py 
 I have made some change from python2 to python3, then i get the following error:

(tensorflow) fei@fei:~/tf-faster-rcnn$ CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo_depre.py 

Traceback (most recent call last):
  File "./tools/demo_depre.py", line 20, in <module>
    from model.test_vgg16 import im_detect
  File "/home/fei/tf-faster-rcnn/tools/../lib/model/test_vgg16.py", line 15, in <module>
    from utils.cython_nms import nms, nms_new
ImportError: /home/fei/tf-faster-rcnn/tools/../lib/utils/cython_nms.so: undefined symbol: _Py_ZeroStruct

How should i solve this problem? i have tried a lot of ways that i find from the Internet.
thanks a lot if anyone can give me a hint

**Comment by endernewton** [comment]
Check this: https://github.com/rbgirshick/py-faster-rcnn/issues/503. 

sometimes a simple Google search is there to help.
