### ISSUE TITLE
What should I do if I want to finetuning?

### ISSUE THREAD

**Issue by wang-tf** [endernewton/tf-faster-rcnn#54]
1. ./lib/datasets/pascal_voc.py  
**self._classes** had be changed

What should I do after that?  
How should I do to change the model?

Now, I have this error:  
>out of memory
invalid argument
an illegal memory access was encountered
an illegal memory access was encountered
E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:656] failed to record completion event; therefore, failed to create inter-stream dependency
I tensorflow/stream_executor/stream.cc:3788] stream 0x54b8220 did not memcpy host-to-device; source: 0x7fd50fe37000
E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:656] failed to record completion event; therefore, failed to create inter-stream dependency
E tensorflow/stream_executor/stream.cc:272] Error recording event in stream: error recording CUDA event on stream 0x54b7400: CUDA_ERROR_ILLEGAL_ADDRESS; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:656] failed to record completion event; therefore, failed to create inter-stream dependency
I tensorflow/stream_executor/stream.cc:3788] stream 0x54b8220 did not memcpy host-to-device; source: 0x7fd50fe46000
E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:656] failed to record completion event; therefore, failed to create inter-stream dependency
I tensorflow/stream_executor/stream.cc:3788] stream 0x54b8220 did not memcpy host-to-device; source: 0x7fd50fe80000
E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:656] failed to record completion event; therefore, failed to create inter-stream dependency
I tensorflow/stream_executor/stream.cc:3788] stream 0x54b8220 did not memcpy host-to-device; source: 0x7fd50fe63000
I tensorflow/stream_executor/stream.cc:3788] stream 0x54b8220 did not memcpy host-to-device; source: 0x7fd50fe0e400
E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:198] Unexpected Event status: 1
Command terminated by signal 6
9.98user 2.68system 0:11.87elapsed 106%CPU (0avgtext+0avgdata 3055576maxresident)k
0inputs+1568outputs (0major+683838minor)pagefaults 0swaps

**Comment by philokey** [comment]
Maybe you don't have enough memory. Can you train on PASCAL VOC successfully?

**Comment by wang-tf** [comment]
Yes, it's successfully on PASCAL VOC. And now I'm training on CPU.   
What should I do if I want to use GPU? My GPU is GTX960 which has 6G memory. Thanks!

**Comment by philokey** [comment]
I think 6G is not enough for res101.  You can reduce batchsize or  try vgg16.

**Comment by wang-tf** [comment]
I will try. Thanks a lot!

**Comment by sevenseablue** [comment]
p100 also found this error
