### ISSUE TITLE
Purpose of subtracting 1 from bounding boxes

### ISSUE THREAD

**Issue by zacwellmer** [endernewton/tf-faster-rcnn#58]
What is the purpose of subtracting 1 from the bounding box corners in pascal_voc.py lines 178, 215, 216, 217, and 218? In the comments it says the purpose is to "Make pixel indexes 0-based" but aren't they already 0 based? Seems like this would cause problems for annotations already located at the 0th x or y coordinate.

**Comment by endernewton** [comment]
I guess VOC is 1-based? I didn't change that from py-faster-rcnn.
