### ISSUE TITLE
online hard example mining? 

### ISSUE THREAD

**Issue by CharlesShang** [endernewton/tf-faster-rcnn#62]
Very solid work!!!

Have you ever tried OHEM?
I've tried it [here](https://github.com/CharlesShang/TFFRCNN), but found no help at all.

**Comment by endernewton** [comment]
Thanks! I also need to learn from you and get the tfrecord/prefetching thing working at least. That should save quite a lot of time for training.

No I haven't. If you are interested, you can try with my current code base and submit a PR. Different implementation can have different results.

**Comment by philokey** [comment]
@CharlesShang I also try OHEM in this repo, nothing helpful, so strange.
