### ISSUE TITLE
Is any difference using conv4 and conv5 for rpn net?

### ISSUE THREAD

**Issue by baiyancheng20** [endernewton/tf-faster-rcnn#64]
@endernewton I found you use the conv5 layer for rpn and fast-rcnn, which is different in the original implementation, using conv4 for rpn. Is there any difference?

Thank you!

**Comment by endernewton** [comment]
For vgg16 we use conv5_3, for resnet we use the last conv4 layer, which is described in the resnet paper. The space for resnet is pretty open though, in FPN they also tried conv5 plus two fc layers, not working so well.

**Comment by baiyancheng20** [comment]
@endernewton  
In [https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/nets/res101.py](url), I think you use the conv_5 layer for rpn.

`self._act_summaries.append(net_conv5)` 
`self._layers[conv5_3] = net_conv5`
   `with tf.variable_scope(resnet_v1_101, resnet_v1_101):`
         `self._anchor_component()`
        `rpn = slim.conv2d(net_conv5, 512, [3, 3], trainable=is_training, weights_initializer=initializer,
                         scope="rpn_conv/3x3")`

**Comment by endernewton** [comment]
I probably need to change the name of that variable. But it is conv 4. double check it yourself.

**Comment by baiyancheng20** [comment]
Thank you. I don't dive into the details and just infer it from its name. Thank you.
