### ISSUE TITLE
Use memory of multiple GPU 

### ISSUE THREAD

**Issue by caunion** [endernewton/tf-faster-rcnn#65]
By default, tf-faster-rcnn will only memory of single GPU, if you have multiple GPUs and hope to use all of them in training, you could comment out `config.gpu_options.allow_growth = True` in lib/model/train_val.py.

**Comment by caunion** [comment]
This issue could be closed, just for other people having simiar problem as I did. :)

**Comment by endernewton** [comment]
Thanks! closing now.

**Comment by baiyancheng20** [comment]
@caunion Just use the memory not the computing ability of each gpu?

**Comment by caunion** [comment]
@baiyancheng20 .No. The computation is on single GPU still. Sorry I forgot to mention that.
I think the current version does not support distribute the computation on multiple GPU.

**Comment by endernewton** [comment]
@caunion you may need to specify multiple devices once you are more familiar with the code.

**Comment by caunion** [comment]
@endernewton you mean specify multiple devices for training?

**Comment by endernewton** [comment]
Yes.
