### ISSUE TITLE
AssertionError: Selective search data not found at: tf-faster-rcnn/data/selective_search_data/voc_2007_trainval.mat

### ISSUE THREAD

**Issue by chakpongchung** [endernewton/tf-faster-rcnn#66]
AssertionError: Selective search data not found at: tf-faster-rcnn/data/selective_search_data/voc_2007_trainval.mat

I am trying to train on my own data with different labels other than the 21 classes in VOC2007, should I download this missing file from somewhere?

**Comment by endernewton** [comment]
i tried to remove the selective search part in the code now. can you retry? normally u just need to set it to gt_roidb.

**Comment by chakpongchung** [comment]
./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc vgg16

Now it is like this:

I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Graphics Device, pci bus id: 0000:02:00.0)
Solving...
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 131, in <module>
    max_iters=args.max_iters)
  File "/data/home/microway/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 378, in train_net
    sw.train_model(sess, max_iters)
  File "/data/home/microway/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 105, in train_model
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "/data/home/microway/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 324, in create_architecture
    val_summaries.append(self._add_image_summary(self._image, self._gt_boxes))
  File "/data/home/microway/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 56, in _add_image_summary
    assert image.get_shape()[0] == 1
AssertionError

**Comment by endernewton** [comment]
you may need to clean up data/cache.

**Comment by chakpongchung** [comment]
Hi,

everytime I run, I clean the cache first. What could go wrong here?

**Comment by endernewton** [comment]
i cannot reproduce your error, so i don't know. :P

**Comment by baiyancheng20** [comment]
Change _C.TRAIN.PROPOSAL_METHOD = 'gt' the 118 line in model/config.py file. It should be OK. 
We also met with this problem. Very weird.

**Comment by endernewton** [comment]
@baiyancheng20 check the new code, i already did that.

**Comment by chakpongchung** [comment]
Thanks, this problem is resolved by using the latest commit.
