### ISSUE TITLE
crop_and_resize vs ROI Align

### ISSUE THREAD

**Issue by zacwellmer** [endernewton/tf-faster-rcnn#67]
Is the current use of crop_and_resize the same as ROI Align used in [Mask RCNN](https://arxiv.org/abs/1703.06870)? Since crop_and_resize uses bilinear interpolation

**Comment by endernewton** [comment]
Besides some subtle differences (maybe), i think in terms of resolving
quantization error, they are the same.

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA

**Comment by zacwellmer** [comment]
Would ROI Align have also have gone straight to 7x7 instead of pooling down to it after the crop_and_resize?

**Comment by endernewton** [comment]
i have actually tried to go straight to 7x7 for vgg16, but it acts worse. for resnet, going 7x7 straight works faster and seem to perform equally well. should have something to do with the original imagenet architecture, where vgg16 uses maxpool, but resnet does not (in conv4).
