### ISSUE TITLE
error when try to load vgg16_depre pretrained on coco 

### ISSUE THREAD

**Issue by caunion** [endernewton/tf-faster-rcnn#71]
Hi, I tried to test the vgg16_depre model pretrained on coco (coco_2014_train+coco_2014_valminusminival 490k) with VOC07 test-set. However, the model and the weight seems does not match as I get an error
`InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [84] rhs shape= [324]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@vgg16_default/bbox_pred/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](vgg16_default/bbox_pred/bias, save/RestoreV2/_61)]]`

I also tried to load the model with `test_faster_rcnn.sh`, I get similar error about weight & model mis-match.

Did I miss anything?

**Comment by endernewton** [comment]
Coco and Voc have different number of classes

**Comment by caunion** [comment]
Can't believe I am so stupid to miss that... >_<
