### ISSUE TITLE
Usage on CPU

### ISSUE THREAD

**Issue by markusnagel** [endernewton/tf-faster-rcnn#72]
I would also like to use Faster RCNN without GPUs. Currently when trying to compile this on a non GPU machine I get the following error:
``` python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 43, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
make: *** [all] Error 1
```
Does anyone have experience on how to make this implementation work without GPUs? Code wise it should probably be possible, I guess it is just adapting the build somehow?

**Comment by shuang1330** [comment]
It might be too late for you, but maybe useful for other people... 1) Change the setup.py file by  replacing all 'raise EnvironmentError' with 'return None', disabling the Extension('nms.gpu_nms'..). 2) Change the lib/model/nms_wrapper.py file by disabling 'import gpu_nms' and setting 'force_cpu' to be True. Above works for me at least.

**Comment by Dinkz** [comment]
HI @shuang1330 

Do you mean, comment out Extension ?
But I am getting error: 
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'

While I run setup.py

**Comment by shuang1330** [comment]
@Dinkz I mean comment out the 'nms.gpu_nms' extension. But your problem seems to be not related to cpu but related to windows

**Comment by ray0809** [comment]
@shuang1330 thanks,according to your advice,it does work

**Comment by markusnagel** [comment]
Thanks for the feedback, I think we can close the issue now.

In the future it might be nice if there is a compile flag, so we do not need to alter code.

**Comment by rida1896** [comment]
I am getting this error too. But I want to use GPU. I am unable to fix it. Please help.

**Comment by fourk-ty** [comment]
@rida1896 Have you fixed it now?

**Comment by shangjianan2** [comment]
@shuang1330 
It is useful. Thanks.

**Comment by yg2015** [comment]
I am getting an error  "'MSVCCompiler' object has no attribute 'compiler_so'", when I am running on Windows. How can I solve it?

**Comment by FrankXinqi** [comment]
> I am getting an error "'MSVCCompiler' object has no attribute 'compiler_so'", when I am running on Windows. How can I solve it?

Same Problem....
