### ISSUE TITLE
problem with vim setup.py

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#73]
I am having a problem when I use the command `vim setup.py`. It says:

> The program 'vim' can be found in the following packages:
>  * vim
>  * vim-gnome
>  * vim-tiny
>  * vim-athena
>  * vim-athena-py2
>  * vim-gnome-py2
>  * vim-gtk
>  * vim-gtk-py2
>  * vim-gtk3
>  * vim-gtk3-py2
>  * vim-nox
>  * vim-nox-py2
> Try: sudo apt install <selected package>

And when I use `python setup.py`, it says:

> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: no commands supplied

How can I run the setup.py file?

**Comment by ljdang** [comment]
@hadi-ghnd This just wants you to edit the "setup.py" file. Choose the editor that you like.

**Comment by philokey** [comment]
1. You should run 
`sudo apt-get install vim`

2.  It's not necessary to run `python setup.py`, just 'make'.  You can refer to `Makeflie`.

**Comment by sxyxf66** [comment]
DO YOU fix it? @hadi-ghnd , I have the same problem. The WINDOW
