### ISSUE TITLE
Training, Testing cleared. But problem in demo

### ISSUE THREAD

**Issue by skywalker023** [endernewton/tf-faster-rcnn#75]
Hello,

I'm trying to train on my own dataset and I have some problems

I trained the model for 3 classes (1 background +2 target classes).

I've done the training and also the testing. It worked fine.

(Mean AP: 0.46. the Mean AP is not fine, I know. I have small dataset) 

But it seems to have a problem in the demo.

```
tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [4096,84] rhs shape= [4096,12]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@vgg_16/bbox_pred/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](vgg_16/bbox_pred/weights, save/RestoreV2_1/_3)]]
```

the lhs shape and rhs shape seems to represent the 21 classes in the original model

and the 3 classes in my dataset.

The fact that I done my testing without errors, it means that I modified my model correctly right?

But I don't get why the demo is causing problems.

Any suggestions..?

**Comment by endernewton** [comment]
you may have to change the demo code L141
