### ISSUE TITLE
tensorboard problem

### ISSUE THREAD

**Issue by chakpongchung** [endernewton/tf-faster-rcnn#77]
I can run the training now. Do I have enough data to run the tensorboard to see the network architecture?
I am planning to retrain and load all but last layer(s) to reuse the feature like people did in caffe prototxt
I cant open the page(http://0.0.0.0:6006) after this:

cpchung@microway:~/experiments/tf-faster-rcnn$ tensorboard --logdir=tensorboard
Starting TensorBoard 47 at http://0.0.0.0:6006

cpchung@microway:~/experiments/tf-faster-rcnn$ tree tensorboard/
tensorboard/
└── default
    └── voc_2007_trainval
        ├── default
        │   ├── events.out.tfevents.1493408816.falcon
        │   ├── events.out.tfevents.1493414152.falcon
        │   ├── events.out.tfevents.1493414252.falcon
        │   ├── events.out.tfevents.1493416493.falcon
        │   ├── events.out.tfevents.1493416639.falcon
        │   ├── events.out.tfevents.1493660877.falcon
        │   ├── events.out.tfevents.1493661169.falcon
        │   ├── events.out.tfevents.1493661616.falcon
        │   ├── events.out.tfevents.1493662351.falcon
        │   ├── events.out.tfevents.1493662672.falcon
        │   ├── events.out.tfevents.1493664885.falcon
        │   ├── events.out.tfevents.1493666778.falcon
        │   ├── events.out.tfevents.1493667940.falcon
        │   ├── events.out.tfevents.1493668037.falcon
        │   ├── events.out.tfevents.1493669128.falcon
        │   ├── events.out.tfevents.1493669289.falcon
        │   ├── events.out.tfevents.1493669307.falcon
        │   ├── events.out.tfevents.1493669661.falcon
        │   ├── events.out.tfevents.1493670106.falcon
        │   ├── events.out.tfevents.1493672118.falcon
        │   ├── events.out.tfevents.1493673879.falcon
        │   ├── events.out.tfevents.1493674507.falcon
        │   ├── events.out.tfevents.1493674577.falcon
        │   ├── events.out.tfevents.1493744693.falcon
        │   ├── events.out.tfevents.1493745290.falcon
        │   ├── events.out.tfevents.1493754210.microway
        │   ├── events.out.tfevents.1493754449.microway
        │   ├── events.out.tfevents.1493754567.microway
        │   ├── events.out.tfevents.1493755536.microway
        │   ├── events.out.tfevents.1493757412.microway
        │   ├── events.out.tfevents.1493759918.microway
        │   ├── events.out.tfevents.1493760690.microway
        │   ├── events.out.tfevents.1493834117.microway
        │   ├── events.out.tfevents.1493834213.microway
        │   ├── events.out.tfevents.1493847152.microway
        │   └── events.out.tfevents.1493847202.microway
        └── default_val
            ├── events.out.tfevents.1493745481.falcon
            ├── events.out.tfevents.1493755807.microway
            ├── events.out.tfevents.1493757598.microway
            ├── events.out.tfevents.1493760104.microway
            ├── events.out.tfevents.1493760878.microway
            └── events.out.tfevents.1493834402.microway

**Comment by endernewton** [comment]
tensorboard --logdir=tensorboard/vgg16/voc_2007_trainval/ --port=7001 &

also ur event list is huge
