### ISSUE TITLE
time python : time not found.

### ISSUE THREAD

**Issue by DeepStillWater** [endernewton/tf-faster-rcnn#89]
when I run the command ./experiments/scripts/test_faster_rcnn.sh $GPU_ID pascal_voc_0712
the error occured like this:
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=0
+ DATASET=pascal_voc_0712
+ NET=
+ array=($@)
+ len=2
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case ${DATASET} in
+ TRAIN_IMDB=voc_2007_trainval+voc_2012_trainval
+ TEST_IMDB=voc_2007_test
+ ITERS=110000
+ ANCHORS='[8,16,32]'
+ RATIOS='[0.5,1,2]'
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/test__voc_2007_trainval+voc_2012_trainval_.txt.2017-05-14_16-39-52
+ exec
++ tee -a experiments/logs/test__voc_2007_trainval+voc_2012_trainval_.txt.2017-05-14_16-39-52
+ echo Logging output to experiments/logs/test__voc_2007_trainval+voc_2012_trainval_.txt.2017-05-14_16-39-52
Logging output to experiments/logs/test__voc_2007_trainval+voc_2012_trainval_.txt.2017-05-14_16-39-52
+ set +x
+ [[ ! -z '' ]]
+ CUDA_VISIBLE_DEVICES=0
+ time python ./tools/test_net.py --imdb voc_2007_test --model output//voc_2007_trainval+voc_2012_trainval/default/_faster_rcnn_iter_110000.ckpt --cfg experiments/cfgs/.yml --net --set ANCHOR_SCALES '[8,16,32]' ANCHOR_RATIOS '[0.5,1,2]'
./experiments/scripts/test_faster_rcnn.sh: 行 66: time: 未找到命令

how an I fix it ,I run 'CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py ',it works well.
please help me.

**Comment by endernewton** [comment]
you can remove that "time" if you find it troublesome

**Comment by DeepStillWater** [comment]
oh,thanks,it works!
