### ISSUE TITLE
Something wrong with running the demo

### ISSUE THREAD

**Issue by paulcx** [endernewton/tf-faster-rcnn#90]
repository root>CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py

Traceback (most recent call last):
  File "./tools/demo.py", line 20, in <module>
    from model.test import im_detect
  File "/home/xx/py/tf-faster-rcnn/tools/../lib/model/test.py", line 20, in <module>
    from utils.cython_nms import nms, nms_new
ImportError: No module named 'utils.cython_nms'

I'm wondering if there is some configs missing?

**Comment by thinkng** [comment]
You can download a suitable cython_nms file from here https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FastRCNN/fastRCNN/utils

**Comment by thinkng** [comment]
Please add these lines to lib/setup.py

 Extension( 
        "utils.cython_nms", 
        sources = ["utils\\nms.pyx"], 
        extra_compile_args={'gcc': []},
        include_dirs = [numpy_include],
    ),

**Comment by summerrr** [comment]
I run the make and the files in lib are 
bbox.c                                       __init__.pyc
bbox.pyx                                     nms.c
blob.py                                      nms.py
boxes_grid.py                                nms.pyx
cython_bbox.cpython-35m-x86_64-linux-gnu.so  __pycache__
cython_nms.cpython-35m-x86_64-linux-gnu.so   timer.py
__init__.py                                  timer.pyc
but I also ImportError: No module named 'utils.cython_nms'
does cython_nms.cpython-35m-x86_64-linux-gnu.so ane  utils.cython_nms' is the same file？
