### ISSUE TITLE
Program halts on resnet_v1.resnet_v1

### ISSUE THREAD

**Issue by Dinkz** [endernewton/tf-faster-rcnn#91]
When the build_network function is entered for training sequence, for resnet 101, the program silently exists upon a call to : resnet_v1.resnet_v1, where cfg.RESNET.FIXED_BLOCKS == 1.

Blocked. Any thoughts why ? TIA.

**Comment by endernewton** [comment]
what is the output look like on your side?

**Comment by Dinkz** [comment]
Hi, there is no output - it is as if it crashes due to lack of memory.

**Comment by endernewton** [comment]
so what is the hardware setup? u can try res50 model if mem is an issue

**Comment by Dinkz** [comment]
It is a p2.xlarge from AWS (1 K8 Tesla with ~12 GB VRAM). Always exits when training is run from the terminal from a VNCSever, on the AWS server. Just realized it does not happen if I connect via PuTTY and do training. Obviously not hardware issue. Weird. But at least not blocked now., since I can use PuTTY.
Now, I am worried if my query is off topic. Do let me know in any case. Thanks a lot!
