### ISSUE TITLE
Not use RPN

### ISSUE THREAD

**Issue by handworker** [endernewton/tf-faster-rcnn#94]
HI, Chen:
    Thanks to your work, I am really benefit from it. Now I want to only use your resnet-101 network trained on coco without RPN (i.e., like fast-rcnn), how could I set it? I find that there is a cfg.TEST.HAS_RPN = True sentence. When i set it to false, it doent work.

**Comment by endernewton** [comment]
no this is not supported. i am implementing fast[ER] rcnn. i will remove the lingering confusing cfg in some time
