### ISSUE TITLE
demo error ...

### ISSUE THREAD

**Issue by perpetmon** [endernewton/tf-faster-rcnn#96]
hi 

i'm newbie in tensorflow 

i try this code  

Demo and Test with pre-trained models

         3.Demo for testing on custom images
           GPU_ID=0
           CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py 

but i see this error...

96] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "./tools/demo.py", line 142, in <module>
    tag='default', anchor_scales=[8, 16, 32])
  File "/home/intlab/endernewton/tf-faster-rcnn/tools/../lib/nets/network.py", line 305, in create_architecture
    rois, cls_prob, bbox_pred = self.build_network(sess, training)
  File "/home/intlab/endernewton/tf-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 156, in build_network
    scope=self._resnet_scope)
  File "/home/intlab/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py", line 212, in resnet_v1
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "/home/intlab/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/intlab/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 216, in stack_blocks_dense
    net = block.unit_fn(net, rate=1, **unit)
TypeError: bottleneck() argument after ** must be a mapping, not tuple

how i can solve it? 
i use anaconda , python 3.6  and tensorflow 1.0 

thank you

**Comment by endernewton** [comment]
maybe your python version is too new? i am not sure

**Comment by perpetmon** [comment]
@endernewton  thank you for feedback  :)  i solve it !

**Comment by kalaspuffar** [comment]
@perpetmon Could you give a hint how you solved it? I've tried with Python 2.7.12 and get the same error.

**Comment by eugene123tw** [comment]
Can someone help me....
I upgrade all my packages in Python 2.7 but still have the same problem...

**Comment by shrishtrived** [comment]
I am having the same issue can anyone help me.

**Comment by fotherda** [comment]
Me too I've tried it with python 3.6 and python 2.7 but get the same error perpetmon reported.

**Comment by zhechen** [comment]
I solved this issue because I found that it is the change of the slim library.  The definition of resnet in lib/resnet_v1.py uses the definition like this: 
blocks = [
        resnet_utils.Block('block1', bottleneck,
                           [(256, 64, 1)] * 2 + [(256, 64, 2)]),
        resnet_utils.Block('block2', bottleneck,
                           [(512, 128, 1)] * 3 + [(512, 128, 2)]),
        # Use stride-1 for the last conv4 layer
        resnet_utils.Block('block3', bottleneck,
                           [(1024, 256, 1)] * 5 + [(1024, 256, 1)]),
        resnet_utils.Block('block4', bottleneck, [(2048, 512, 1)] * 3)
      ]

This is incompatible with the new slim library, which accepts dictionary rather than tuple or list.

**Comment by endernewton** [comment]
Thanks! could you submit a PR @zhechen.

-Xinlei

**Comment by fotherda** [comment]
Thanks zhechen. Could you say exactly which version of slim it didn't work with and which one it does?

**Comment by zhechen** [comment]
Hi, everyone
    I am now using the most recent version of tensorflow (1.2) and the
resnet_v1 will fail to construct network using the codes like this:
     #===============================
     # res50
     blocks = [
        resnet_utils.Block('block1', bottleneck,
                           [(256, 64, 1)] * 2 + [(256, 64, 2)]),
        resnet_utils.Block('block2', bottleneck,
                           [(512, 128, 1)] * 3 + [(512, 128, 2)]),
        # Use stride-1 for the last conv4 layer
        resnet_utils.Block('block3', bottleneck,
                           [(1024, 256, 1)] * 5 + [(1024, 256, 1)]),
        resnet_utils.Block('block4', bottleneck, [(2048, 512, 1)] * 3)
      ]
     #===============================

    The error comes from the resnet_v1 under slim lib in my tensorflow.
Afterward, I follow the slim to construct resnet. The codes are like this:

     #===============================
    ###
    def resnet_v1_block(scope, bottleneck, base_depth, num_units, stride):
      return resnet_utils.Block(scope, bottleneck, [{
          'depth': base_depth * 4,
          'depth_bottleneck': base_depth,
          'stride': 1
      }] * (num_units - 1) + [{
          'depth': base_depth * 4,
          'depth_bottleneck': base_depth,
          'stride': stride
      }])
    ###
    def build_network(...):
        ...
        # res 50
        blocks = [resnet_v1_block('block1', bottleneck, base_depth=64,
num_units=3, stride=2)
        blocks = [resnet_v1_block('block2', bottleneck, base_depth=128,
num_units=4, stride=2)
        # use stride 1 for the last conv4 layer
        blocks = [resnet_v1_block('block3', bottleneck, base_depth=256,
num_units=6, stride=1)
        blocks = [resnet_v1_block('block4', bottleneck, base_depth=512,
num_units=3, stride=1)

     #===============================

    This solved issue for me. However, I have not evaluated the model.

    I am new to this wonderful project and I am now also studying the
recent rcnns.
    I am happy to help solve the problem and discuss with you ~

   Thanks!

Best,
Zhe

**Comment by zhechen** [comment]
Sorry, the modified codes are not arranged correctly, it should like this:
        # res 50
        blocks = [resnet_v1_block('block1', bottleneck, base_depth=64,
num_units=3, stride=2),
                       resnet_v1_block('block2', bottleneck,
base_depth=128, num_units=4, stride=2),
                       # use stride 1 for the last conv4 layer
                       resnet_v1_block('block3', bottleneck,
base_depth=256, num_units=6, stride=1),
                       resnet_v1_block('block4', bottleneck,
base_depth=512, num_units=3, stride=1),
       ]

**Comment by fotherda** [comment]
Thanks for that info zhechen. 

endernewton could you specify which version of tensorflow this does work with so users have the option of downgrading their tf version rather than updating the code? Thanks

**Comment by shrishtrived** [comment]
@ zhechen  Where and which files do and I need to change for code to run can you please tell, I am not able to figure out . Do I need to change the files in tf-faster-rcnn directory or the tensorflow lib.
Thank you.

**Comment by syy1017** [comment]
[](url)

> Thanks for that info zhechen.
> 
> endernewton could you specify which version of tensorflow this does work with so users have the option of downgrading their tf version rather than updating the code?
> 
> Update: I've tried with 0.12.0 - doesn't work, 1.0.0 does work, 1.2.0 doesn't work. Hopefully this narrows down the search range for people navigating these versioning issues.

thanks a lot！you solved my issue，1.0.0 does work！
