### ISSUE TITLE
change nms_threshold dose not eliminate bbox overlapped a lot for same calss

### ISSUE THREAD

**Issue by JRCondeNast** [endernewton/tf-faster-rcnn#98]
Hi I used the pre-trained restnet101 for coco data and copy the demo and changed classes and anchor box staff. But by changing nms_threshold, I still get overlapped a lot bbox for one class. It seems none maximum suppression dosen't work? Any thought?

**Comment by endernewton** [comment]
you probably didn't compile the nms code properly. you can try to set USE_GPU_NMS False.

**Comment by JRCondeNast** [comment]
Thanks. I have a kepler architecture GPU which should be sm_35. Thanks.

**Comment by JRCondeNast** [comment]
Btw, it would be nice if we can include this in README.md :http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
